export const ttsSttMusicV53Endpoints = {
  api_admin_music_speech_v53_review_center: "/api/admin/music-speech/v53/review-center",
  api_ops_vps_v53_evidence_backfill: "/api/ops/vps/v53/evidence-backfill",
  api_admin_speech_training_v53_legal_batch: "/api/admin/speech-training/v53/legal-batch",
  api_ops_search_music_v53_ranking_upgrade: "/api/ops/search/music/v53/ranking-upgrade",
  api_ops_authority_sources_v53_publication: "/api/ops/authority-sources/v53/publication",
  api_ops_speech_training_v53_model_seal: "/api/ops/speech-training/v53/model-seal",
  api_ops_site_v53_formal_monitoring: "/api/ops/site/v53/formal-monitoring",
  api_ops_vps_v53_preflight_contract: "/api/ops/vps/v53/preflight-contract",
  api_ops_next_upgrade_plan_v54: "/api/ops/next-upgrade-plan/v54",
  api_public_music_metadata_v53_cards: "/api/public/music/metadata/v53/cards",
  api_internal_vps_v53_record_health_evidence: "/api/internal/vps/v53/record-health-evidence",
  api_internal_vps_v53_record_dns_evidence: "/api/internal/vps/v53/record-dns-evidence",
  api_internal_vps_v53_record_backup_restore_evidence: "/api/internal/vps/v53/record-backup-restore-evidence",
  api_internal_vps_v53_record_observation_window: "/api/internal/vps/v53/record-observation-window",
  api_internal_vps_v53_seal_backfill_report: "/api/internal/vps/v53/seal-backfill-report",
  api_internal_speech_training_v53_attach_evidence_file: "/api/internal/speech-training/v53/attach-evidence-file",
  api_internal_speech_training_v53_approve_legal_asset: "/api/internal/speech-training/v53/approve-legal-asset",
  api_internal_speech_training_v53_export_legal_batch: "/api/internal/speech-training/v53/export-legal-batch",
  api_internal_speech_training_v53_record_native_speaker_review: "/api/internal/speech-training/v53/record-native-speaker-review",
  api_internal_search_music_v53_record_ranking_metric: "/api/internal/search/music/v53/record-ranking-metric",
  api_internal_search_music_v53_approve_ranking_rollout: "/api/internal/search/music/v53/approve-ranking-rollout",
  api_internal_search_music_v53_rollback_ranking_rollout: "/api/internal/search/music/v53/rollback-ranking-rollout",
  api_internal_search_music_v53_create_synonym_merge_task: "/api/internal/search/music/v53/create-synonym-merge-task",
  api_internal_authority_sources_v53_publish_metadata_card: "/api/internal/authority-sources/v53/publish-metadata-card",
  api_internal_authority_sources_v53_record_source_change: "/api/internal/authority-sources/v53/record-source-change",
  api_internal_authority_sources_v53_test_takedown_flow: "/api/internal/authority-sources/v53/test-takedown-flow",
  api_internal_speech_training_v53_render_governance_pdf: "/api/internal/speech-training/v53/render-governance-pdf",
  api_internal_speech_training_v53_record_signoff_section: "/api/internal/speech-training/v53/record-signoff-section",
  api_internal_speech_training_v53_record_lineage_dag: "/api/internal/speech-training/v53/record-lineage-dag",
  api_internal_speech_training_v53_close_release_blocker: "/api/internal/speech-training/v53/close-release-blocker",
  api_internal_site_v53_record_uptime_sample: "/api/internal/site/v53/record-uptime-sample",
  api_internal_site_v53_record_error_rate: "/api/internal/site/v53/record-error-rate",
  api_internal_site_v53_record_lighthouse_run: "/api/internal/site/v53/record-lighthouse-run",
  api_internal_site_v53_create_ops_report: "/api/internal/site/v53/create-ops-report",
  api_internal_site_v53_send_alert_notification: "/api/internal/site/v53/send-alert-notification",
} as const;
export type TtsSttMusicV53Endpoint = keyof typeof ttsSttMusicV53Endpoints;
