-- Seed: Pinuyumayan Ten Communities
INSERT INTO pinuyumayan_communities (id, community_key, sort_order, name_zh, romanization, origin_system, administrative_hint, platform_summary, content_focus_json, source_ids_json, review_status) VALUES
('community_puyuma','puyuma',1,'南王','Puyuma','竹生系統','臺東市南王里','南王是卑南族重要核心部落之一；平台中 Puyuma 僅指南王部落或英文語境中的卑南語，不可用來代稱整個卑南族。',CAST('["年祭", "少年年祭", "大獵祭", "巫師祭", "海祭/小米收穫祭", "音樂人才"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('community_katratripulr','katratripulr',2,'知本','Katratripulr','石生系統','臺東市知本里','知本是石生系統的重要核心，與建和等部落在起源敘事與四月祭祖脈絡中常被並讀。',CAST('["石生起源", "祖先登陸與發祥地祭祖", "收穫祭", "會所復振", "知本卑南語"]' AS JSON),CAST('["cip_puyuma_profile", "formosanbank_dialects_csv"]' AS JSON),'approved'),
('community_kasavakan','kasavakan',3,'建和','Kasavakan','石生系統','臺東市建和里','建和以祭祖、收穫祭與年祭脈絡重要；語料上對應 FormosanBank Jianhe_Puyuma。',CAST('["祖先登陸與發祥地祭祖", "小米收穫祭", "年祭", "巨型鞦韆", "建和卑南語"]' AS JSON),CAST('["cip_puyuma_profile", "formosanbank_dialects_csv"]' AS JSON),'approved'),
('community_likavung','likavung',4,'利嘉','Likavung','石生系統','臺東縣卑南鄉利嘉村','利嘉在平台中宜放入年祭、除喪、階級制度與歌舞復振等主題脈絡。',CAST('["年祭", "除喪", "部落階級制度", "傳統歌舞"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('community_ulivelivek','ulivelivek',5,'初鹿','Ulivelivek','石生系統','臺東縣卑南鄉初鹿村','初鹿與西群卑南語脈絡關聯高；內容可強化會所、收穫祭與鞦韆文化特色。',CAST('["收穫祭", "盪鞦韆", "年祭", "會所", "西群卑南語"]' AS JSON),CAST('["cip_puyuma_profile", "formosanbank_dialects_csv"]' AS JSON),'approved'),
('community_tamalakaw','tamalakaw',6,'泰安','Tamalakaw','石生系統','臺東縣卑南鄉泰安村/太平村脈絡','泰安宜列入大獵祭、石生系統與部落治理脈絡；羅馬拼音以 Tamalakaw 為平台主用。',CAST('["大獵祭", "石生系統", "部落治理"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('community_pinaski','pinaski',7,'下賓朗','Pinaski','石生系統','臺東縣卑南鄉賓朗村','下賓朗內容可強化婦女除草完工慶、部落保守性與花環文化；Pinarai 類別名需人工複核。',CAST('["婦女除草完工慶", "收穫祭", "年祭", "花環文化"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('community_danadanaw','danadanaw',8,'龍過脈','Danadanaw','石生系統','臺東縣卑南鄉明峰村脈絡','龍過脈適合作為十社地理與遷徙脈絡的補強內容；細節公開前需部落複核。',CAST('["遷徙記憶", "初鹿地區脈絡", "部落地理"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('community_rarangus','rarangus',9,'班鳩','Rarangus','石生系統','文獻常記為已遷併入初鹿脈絡','班鳩在平台權威表中不可省略；公開細節與當代狀態需保留複核欄位。',CAST('["遷併記憶", "十社補遺", "平台正名"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('community_papulu','papulu',10,'寶桑','Papulu','竹生系統','臺東市寶桑里','寶桑可放入臺東市區部落、竹生系統與大獵祭脈絡；Papulu 為平台主用版。',CAST('["大獵祭", "都市部落", "文化延續"]' AS JSON),CAST('["cip_puyuma_profile"]' AS JSON),'approved')
ON DUPLICATE KEY UPDATE updated_at=CURRENT_TIMESTAMP;

INSERT INTO pinuyumayan_community_aliases (id, community_key, alias_text, alias_type, usage_note, allowed_for_public_search, allowed_for_primary_display) VALUES
('alias_5930a6d76bdbb40a','puyuma','Nanwang','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_32962dd5d92a2942','puyuma','南王部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_b09b67cf4d734705','puyuma','卑南社','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_6a913f863d8d7df8','puyuma','普悠瑪部落','deprecated','警示：不得作為族群正式名稱',TRUE,FALSE),
('alias_75174aaa5e457505','katratripulr','Katipul','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_7544227518a9e62c','katratripulr','Katratipul','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_d0111c65cc250447','katratripulr','Katripul','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_efb8c6da43b32d52','katratripulr','Zhiben','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_d634d2e56d705b88','katratripulr','卡大地布','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_4ccb89b63ff27147','kasavakan','Jianhe','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_b921b377f967f345','kasavakan','Samagan','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_02ba51bc60fe5923','kasavakan','射馬干','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_a3bd65663c3ce98b','kasavakan','建和部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_a026a3ecc4a5e432','likavung','Likavong','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_d3798856cdb67e70','likavung','Lijia','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_f5992076b4daa2f6','likavung','呂家望','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_feffe4b444ec8e06','likavung','利嘉部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_9a71d100afa63a63','ulivelivek','Mulivelivek','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_1226dab901cf56ff','ulivelivek','Chulu','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_868dc3719d6f841c','ulivelivek','北絲鬮','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_a362f43e89eca1ed','ulivelivek','初鹿部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_1a7a7be43b97156b','tamalakaw','Tamalrakaw','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_88ab7b5cdd43c008','tamalakaw','Damalagaw','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_fd0ff48b3b768e61','tamalakaw','Taian','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_91c1ee51ba08f03e','tamalakaw','大巴六九','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_c3783a67dc31bc9a','pinaski','Pinaseki','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_3cd5940daa16a778','pinaski','Pinarai','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_4db9cbd9c98469c2','pinaski','Xiabinglang','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_a2c1058f0731d988','pinaski','檳榔樹格','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_f9b0138c22653932','danadanaw','Longguomai','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_4d909373a68500e9','danadanaw','明峰村脈絡','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_934b6267739a2db8','danadanaw','龍過脈部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_afc47242223ac5f4','rarangus','Banjou','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_2916c9f90fa68850','rarangus','班鳩部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_81abc6706cefd36b','papulu','Apapolo','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_737b1696fbc0826f','papulu','Baosang','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_145e08ceb8c5e704','papulu','巴布麓','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE),
('alias_e29890bbf5f51339','papulu','寶桑部落','common','別名/搜尋用；不得覆蓋主用版',TRUE,FALSE)
ON DUPLICATE KEY UPDATE alias_text=VALUES(alias_text);
