-- Seed: rituals public summaries
INSERT INTO pinuyumayan_rituals (id, name_zh, category, time_hint, summary, communities_json, platform_tags_json, visibility, sensitivity, source_ids_json, review_status) VALUES
('women_weeding_completion','婦女除草完工慶','農事祭儀/婦女組織','國曆3月；實際日期依部落公告','與農事除草工作完成相關，凸顯婦女團體、祈福、團結與休閒活動。',CAST('["pinaski", "puyuma", "other_review_required"]' AS JSON),CAST('["農事", "婦女", "祈福", "部落團結"]' AS JSON),'public_summary_only','medium',CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('ancestral_landing_foundation_rite','祖先登陸與發祥地祭祖','祖源/祭祖','國曆4月；實際日期依部落公告','知本、建和等部落會到祖先登陸地或發祥地祭祀歷代祖先，呈現慎終追遠與起源記憶。',CAST('["katratripulr", "kasavakan"]' AS JSON),CAST('["起源", "祭祖", "發祥地", "石生系統"]' AS JSON),'public_summary_only','high',CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('millet_harvest_rite','小米收穫祭','農事祭儀','國曆7月；部落可能為3至7天不等','以家族與部落為單位感謝收穫，與小米、祭司、婦女角色、祈福及部落活動相關。',CAST('["puyuma", "katratripulr", "kasavakan", "ulivelivek", "pinaski", "other_review_required"]' AS JSON),CAST('["小米", "收穫", "感恩", "家族", "祈福"]' AS JSON),'public_summary_only','medium',CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('annual_festival','年祭','歲時祭儀/生命禮俗','國曆12月；部分部落延續至跨年脈絡','卑南族最重要的年度活動之一，常包含少年年祭、大獵祭、慶功、除喪與部落團聚。',CAST('["all_review_by_community"]' AS JSON),CAST('["年祭", "部落團聚", "會所", "除喪", "花環"]' AS JSON),'public_summary_only','medium',CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('mangamangayaw_youth_rite','少年年祭','年齡階級/少年訓練','多在12月下旬；依部落公告','與少年膽識、會所訓練及成年過程相關；現代公開活動多以象徵方式延續，不使用真猴。',CAST('["puyuma", "ulivelivek", "pinaski", "other_review_required"]' AS JSON),CAST('["少年", "會所", "膽識", "文化教育"]' AS JSON),'public_summary_only','medium',CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('mangayaw_great_hunting_rite','大獵祭','成年/狩獵/年祭','國曆12月下旬；部落可能不同','與男子成年、野外求生、狩獵訓練、凱旋迎接與部落慰問相關，是年祭核心內容之一。',CAST('["puyuma", "tamalakaw", "papulu", "other_review_required"]' AS JSON),CAST('["大獵祭", "成年", "狩獵", "野外求生", "凱旋門"]' AS JSON),'public_summary_only','high',CAST('["cip_puyuma_profile"]' AS JSON),'approved'),
('united_annual_festival','聯合年祭','跨部落交流','時間不定；由部落聯合會議或主辦單位公告','由各部落輪流或共同辦理，以歌舞、競賽與交流凝聚卑南族共同體意識。',CAST('["all_review_by_community"]' AS JSON),CAST('["聯合年祭", "十社", "歌舞", "交流", "族群凝聚"]' AS JSON),'public_summary_only','medium',CAST('["cip_puyuma_profile"]' AS JSON),'approved')
ON DUPLICATE KEY UPDATE updated_at=CURRENT_TIMESTAMP;
