-- v46 authority source governance seed
INSERT IGNORE INTO authority_source_fetch_policies_v46 (adapter_id, robots_txt_url, tos_review_status, etag_enabled, if_modified_since_enabled, rate_limit_per_minute, policy_json) VALUES ('taiwan_music_institute', 'https://tmi.openmuseum.tw/robots.txt', 'needs_human_record', TRUE, TRUE, 12, CAST('{"adapter_id": "taiwan_music_institute", "name": "臺灣音樂館", "base_url": "https://tmi.openmuseum.tw/", "robots_txt_url": "https://tmi.openmuseum.tw/robots.txt", "tos_review_status": "needs_human_record", "etag_enabled": true, "if_modified_since_enabled": true, "rate_limit_per_minute": 12, "respect_retry_after_header": true, "max_parallel_requests": 1, "never_fetch": ["audio_binary", "video_binary", "full_lyrics", "restricted_ritual_detail", "private_person_data"], "candidate_auto_public": false}' AS JSON));
INSERT IGNORE INTO authority_source_fetch_policies_v46 (adapter_id, robots_txt_url, tos_review_status, etag_enabled, if_modified_since_enabled, rate_limit_per_minute, policy_json) VALUES ('national_culture_memory_bank', 'https://memory.culture.tw/robots.txt', 'needs_human_record', TRUE, TRUE, 10, CAST('{"adapter_id": "national_culture_memory_bank", "name": "國家文化記憶庫", "base_url": "https://memory.culture.tw/", "robots_txt_url": "https://memory.culture.tw/robots.txt", "tos_review_status": "needs_human_record", "etag_enabled": true, "if_modified_since_enabled": true, "rate_limit_per_minute": 10, "respect_retry_after_header": true, "max_parallel_requests": 1, "never_fetch": ["audio_binary", "video_binary", "full_lyrics", "restricted_ritual_detail", "private_person_data"], "candidate_auto_public": false}' AS JSON));
INSERT IGNORE INTO authority_source_fetch_policies_v46 (adapter_id, robots_txt_url, tos_review_status, etag_enabled, if_modified_since_enabled, rate_limit_per_minute, policy_json) VALUES ('golden_melody_awards', 'https://gma.tavis.tw/robots.txt', 'needs_human_record', TRUE, TRUE, 8, CAST('{"adapter_id": "golden_melody_awards", "name": "金曲獎", "base_url": "https://gma.tavis.tw/", "robots_txt_url": "https://gma.tavis.tw/robots.txt", "tos_review_status": "needs_human_record", "etag_enabled": true, "if_modified_since_enabled": true, "rate_limit_per_minute": 8, "respect_retry_after_header": true, "max_parallel_requests": 1, "never_fetch": ["audio_binary", "video_binary", "full_lyrics", "restricted_ritual_detail", "private_person_data"], "candidate_auto_public": false}' AS JSON));
INSERT IGNORE INTO authority_source_retry_queue_v46 (retry_id, adapter_id, status, attempt, reason, retry_json) VALUES ('auth-retry-v46-001', 'taiwan_music_institute', 'queued_manual_dry_run', 0, 'verify_robots_tos_etag_before_fetch', CAST('{"retry_id": "auth-retry-v46-001", "adapter_id": "taiwan_music_institute", "status": "queued_manual_dry_run", "attempt": 0, "next_run_reason": "verify_robots_tos_etag_before_fetch", "backoff_seconds": 0}' AS JSON));
INSERT IGNORE INTO authority_source_retry_queue_v46 (retry_id, adapter_id, status, attempt, reason, retry_json) VALUES ('auth-retry-v46-002', 'national_culture_memory_bank', 'queued_manual_dry_run', 0, 'verify_robots_tos_etag_before_fetch', CAST('{"retry_id": "auth-retry-v46-002", "adapter_id": "national_culture_memory_bank", "status": "queued_manual_dry_run", "attempt": 0, "next_run_reason": "verify_robots_tos_etag_before_fetch", "backoff_seconds": 0}' AS JSON));
INSERT IGNORE INTO authority_source_retry_queue_v46 (retry_id, adapter_id, status, attempt, reason, retry_json) VALUES ('auth-retry-v46-003', 'golden_melody_awards', 'queued_manual_dry_run', 0, 'verify_robots_tos_etag_before_fetch', CAST('{"retry_id": "auth-retry-v46-003", "adapter_id": "golden_melody_awards", "status": "queued_manual_dry_run", "attempt": 0, "next_run_reason": "verify_robots_tos_etag_before_fetch", "backoff_seconds": 0}' AS JSON));
INSERT IGNORE INTO authority_source_candidate_merge_requests_v46 (merge_request_id, adapter_id, merge_status, merge_json, public_auto_release) VALUES ('auth-merge-v46-001', 'taiwan_music_institute', 'needs_candidates', CAST('{"merge_request_id": "auth-merge-v46-001", "adapter_id": "taiwan_music_institute", "candidate_ids": [], "merge_status": "needs_candidates", "decision_required_by_role": "music_candidate_reviewer", "public_auto_release": false}' AS JSON), FALSE);
INSERT IGNORE INTO authority_source_candidate_merge_requests_v46 (merge_request_id, adapter_id, merge_status, merge_json, public_auto_release) VALUES ('auth-merge-v46-002', 'national_culture_memory_bank', 'needs_candidates', CAST('{"merge_request_id": "auth-merge-v46-002", "adapter_id": "national_culture_memory_bank", "candidate_ids": [], "merge_status": "needs_candidates", "decision_required_by_role": "music_candidate_reviewer", "public_auto_release": false}' AS JSON), FALSE);
INSERT IGNORE INTO authority_source_candidate_merge_requests_v46 (merge_request_id, adapter_id, merge_status, merge_json, public_auto_release) VALUES ('auth-merge-v46-003', 'golden_melody_awards', 'needs_candidates', CAST('{"merge_request_id": "auth-merge-v46-003", "adapter_id": "golden_melody_awards", "candidate_ids": [], "merge_status": "needs_candidates", "decision_required_by_role": "music_candidate_reviewer", "public_auto_release": false}' AS JSON), FALSE);
