-- v48 VPS DB validation seed
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-migration-0043-present','v48-contract-report','migration-0043-present','pending_vps_run','all v47 tables exist',NULL,CAST('{"check_id": "migration-0043-present", "name": "0043 migration applied", "status": "pending_vps_run", "expected": "all v47 tables exist", "command": "SHOW TABLES LIKE ..."}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-migration-0044-present','v48-contract-report','migration-0044-present','pending_vps_run','all v48 tables exist',NULL,CAST('{"check_id": "migration-0044-present", "name": "0044 migration applied", "status": "pending_vps_run", "expected": "all v48 tables exist", "command": "SHOW TABLES LIKE ..."}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-transaction-commit','v48-contract-report','transaction-commit','contract_ready','successful review action commits audit row',NULL,CAST('{"check_id": "transaction-commit", "name": "commit path", "status": "contract_ready", "expected": "successful review action commits audit row", "case_id": "tx-commit-review-action"}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-transaction-rollback','v48-contract-report','transaction-rollback','contract_ready','invalid alignment rolls back queue/audit writes',NULL,CAST('{"check_id": "transaction-rollback", "name": "rollback path", "status": "contract_ready", "expected": "invalid alignment rolls back queue/audit writes", "case_id": "tx-rollback-alignment-score"}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-idempotency','v48-contract-report','idempotency','contract_ready','duplicate idempotency key does not create duplicate audit rows',NULL,CAST('{"check_id": "idempotency", "name": "idempotency replay", "status": "contract_ready", "expected": "duplicate idempotency key does not create duplicate audit rows", "case_id": "tx-idempotency-review-action"}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-audit-immutable','v48-contract-report','audit-immutable','contract_ready','audit row cannot be overwritten by repeated write',NULL,CAST('{"check_id": "audit-immutable", "name": "audit immutability", "status": "contract_ready", "expected": "audit row cannot be overwritten by repeated write", "case_id": "tx-audit-immutable"}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-query-log-write','v48-contract-report','query-log-write','contract_ready','v43 search records into v47/v48 analytics pipeline',NULL,CAST('{"check_id": "query-log-write", "name": "search query log write", "status": "contract_ready", "expected": "v43 search records into v47/v48 analytics pipeline", "case_id": "search-log-aggregate"}' AS JSON));
INSERT IGNORE INTO vps_db_validation_check_results_v48 (result_id, report_id, check_id, status, expected_result, actual_result, check_json) VALUES ('result-authority-fetch','v48-contract-report','authority-fetch','manual_gate_required','metadata-only candidates require merge review before public use',NULL,CAST('{"check_id": "authority-fetch", "name": "authority metadata fetch", "status": "manual_gate_required", "expected": "metadata-only candidates require merge review before public use", "case_id": "authority-fetch-merge"}' AS JSON));
