import { registerFrontendAiArticleRoutes } from './rest/frontendAiArticleRoutes';

import { registerAdminAuthDbV26Routes } from "./rest/adminAuthDbV26Routes";
import { registerInternalSecurityV26Routes } from "./rest/internalSecurityV26Routes";
import { registerArticleReviewDbV26Routes } from "./rest/articleReviewDbV26Routes";
import { registerVpsDatabaseV26Routes } from "./rest/vpsDatabaseV26Routes";
import { registerVpsStagingV27Routes } from "./rest/vpsStagingV27Routes";
import { registerVpsLiveOpsV28Routes } from "./rest/vpsLiveOpsV28Routes";
import { registerVpsActualOpsV29Routes } from "./rest/vpsActualOpsV29Routes";
import { registerProductionCutoverV30Routes } from "./rest/productionCutoverV30Routes";
import { registerProductionDryRunV31Routes } from "./rest/productionDryRunV31Routes";
import { registerVpsDryRunBackfillV32Routes } from "./rest/vpsDryRunBackfillV32Routes";
import { registerExpandedSourceSearchV33Routes } from "./rest/expandedSourceSearchV33Routes";
import { registerExpandedTrueKnowledgeV34Routes } from "./rest/expandedTrueKnowledgeV34Routes";
import { registerMusicYoutubeKnowledgeV35Routes } from "./rest/musicYoutubeKnowledgeV35Routes";
import { registerMusicSongCatalogV36Routes } from "./rest/musicSongCatalogV36Routes";
import { registerMusicFolkSongCatalogV37Routes } from "./rest/musicFolkSongCatalogV37Routes";
import { registerMusicFolkSongDeepV38Routes } from "./rest/musicFolkSongDeepV38Routes";
import { registerMusicFolkSongExpansionV39Routes } from "./rest/musicFolkSongExpansionV39Routes";
import { registerMusicFolkSongExpansionV40Routes } from "./rest/musicFolkSongExpansionV40Routes";
import { registerTtsSttMusicOpsV41Routes } from "./rest/ttsSttMusicOpsV41Routes";
import { registerTtsSttEvalMusicSearchV42Routes } from "./rest/ttsSttEvalMusicSearchV42Routes";
import { registerTtsSttLiveMusicV43Routes } from "./rest/ttsSttLiveMusicV43Routes";
import { enforceInternalHmacV32 } from "./security/enforceInternalHmacV32";
import "dotenv/config";
import express from "express";
import helmet from "helmet";
import cors from "cors";
import { createExpressMiddleware } from "@trpc/server/adapters/express";
import { appRouter } from "./trpc/root";
import { createContext } from "./trpc/context";
import { registerMainSiteKnowledgeRoutes } from "./rest/mainSiteKnowledgeRoutes";
import { registerOpenApiRoutes } from "./rest/openapiRoutes";
import { registerRuntimeOpsRoutes } from "./rest/runtimeOpsRoutes";
import { registerReadinessRoutes } from "./rest/readinessRoutes";
import { registerJobsRoutes } from "./rest/jobsRoutes";
import { registerSyncReplayRoutes } from "./rest/syncReplayRoutes";
import { registerExportRoutes } from "./rest/exportRoutes";
import { registerVersionRoutes } from "./rest/versionRoutes";
import { registerAdminAuthRoutes } from "./rest/adminAuthRoutes";
import { registerAdminSyncRoutes } from "./rest/adminSyncRoutes";
import { registerContentRoutes } from "./rest/contentRoutes";
import { registerSearchRoutes } from "./rest/searchRoutes";
import { registerReleaseRoutes } from "./rest/releaseRoutes";
import { registerObservabilityRoutes } from "./rest/observabilityRoutes";
import { registerContractRoutes } from "./rest/contractRoutes";
import { registerCorpusReconciliationRoutes } from "./rest/corpusReconciliationRoutes";
import { registerSecurityOpsRoutes } from "./rest/securityOpsRoutes";
import { registerPronunciationRoutes } from "./rest/pronunciationRoutes";
import { registerAudioRoutes } from "./rest/audioRoutes";
import { registerAiArticleRoutes } from "./rest/aiArticleRoutes";
import { registerMainSiteRuntimeBridgeV24Routes } from "./rest/mainSiteRuntimeBridgeV24Routes";
import { registerArticleReviewV25Routes } from "./rest/articleReviewV25Routes";
import { registerMainSiteMigrationV25Routes } from "./rest/mainSiteMigrationV25Routes";
import { requestIdMiddleware } from "./lib/requestId";
import { createMemoryRateLimit, cleanupRateLimitBuckets } from "./security/rateLimit";
import { env, assertProductionEnv } from "./lib/env";

assertProductionEnv();
const app = express();
app.use(helmet());
app.use(requestIdMiddleware);
app.use(cors({ origin: env.corsOrigin === "*" ? true : env.corsOrigin.split(",") }));
app.use(express.json({ limit: "2mb" }));
app.use("/api/public", createMemoryRateLimit({ windowMs: 60_000, max: env.publicRateLimitPerMinute, keyPrefix: "public" }));
app.use("/api/internal", createMemoryRateLimit({ windowMs: 60_000, max: env.internalRateLimitPerMinute, keyPrefix: "internal" }));
app.use("/api/internal", enforceInternalHmacV32());
setInterval(cleanupRateLimitBuckets, 60_000).unref();

app.get("/health", (_req, res) => {
  res.json({ ok: true, service: "pinuyumayan-backend-database", mode: process.env.NODE_ENV ?? "development" });
});

registerMainSiteKnowledgeRoutes(app, createContext);
registerFrontendAiArticleRoutes(app);
registerOpenApiRoutes(app);
registerRuntimeOpsRoutes(app);
registerReadinessRoutes(app);
registerJobsRoutes(app);
registerSyncReplayRoutes(app);
registerExportRoutes(app);
registerVersionRoutes(app);
registerAdminAuthRoutes(app);
registerAdminSyncRoutes(app);
registerContentRoutes(app);
registerSearchRoutes(app);
registerReleaseRoutes(app);
registerObservabilityRoutes(app);
registerContractRoutes(app);
registerCorpusReconciliationRoutes(app);
registerSecurityOpsRoutes(app);
registerPronunciationRoutes(app);
registerAudioRoutes(app);
registerAiArticleRoutes(app);
registerMainSiteRuntimeBridgeV24Routes(app);
registerArticleReviewV25Routes(app);
registerMainSiteMigrationV25Routes(app);
registerAdminAuthDbV26Routes(app);
registerInternalSecurityV26Routes(app);
registerArticleReviewDbV26Routes(app);
registerVpsDatabaseV26Routes(app);
registerVpsStagingV27Routes(app);
registerVpsLiveOpsV28Routes(app);
registerVpsActualOpsV29Routes(app);
registerProductionCutoverV30Routes(app);
registerProductionDryRunV31Routes(app);
registerVpsDryRunBackfillV32Routes(app);
registerExpandedSourceSearchV33Routes(app);
registerExpandedTrueKnowledgeV34Routes(app);
registerMusicYoutubeKnowledgeV35Routes(app);
registerMusicSongCatalogV36Routes(app);
registerMusicFolkSongCatalogV37Routes(app);
registerMusicFolkSongDeepV38Routes(app);
registerMusicFolkSongExpansionV39Routes(app);
registerMusicFolkSongExpansionV40Routes(app);
registerTtsSttMusicOpsV41Routes(app);
registerTtsSttEvalMusicSearchV42Routes(app);
registerTtsSttLiveMusicV43Routes(app);

app.use("/trpc", createExpressMiddleware({ router: appRouter, createContext }));

const port = env.port;
app.listen(port, () => {
  console.log(`Pinuyumayan backend database API listening on :${port}`);
});
