#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, hashlib
from pathlib import Path
ROOT=Path.cwd()
blocked_terms=['卑南文化遺址','卑南遺址','卑南考古遺址','卑南文化公園','Peinan Site','Beinan Site','Peinan Archaeological Site']

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--dry-run', action='store_true', default=True)
    args=ap.parse_args()
    contract=json.loads((ROOT/'data/integration/authority_source_worker_v45.json').read_text(encoding='utf-8'))
    candidates=[]; runs=[]
    for adapter in contract.get('adapters', []):
        run_id='auth-run-v45-'+hashlib.sha256(adapter['adapter_id'].encode()).hexdigest()[:12]
        count=0
        for q in adapter.get('queries', []):
            title=f"{adapter['name']} metadata candidate: {q}"
            canonical_url=f"{adapter['base_url'].rstrip('/')}/search?q={q}"
            dedupe=hashlib.sha256((adapter['adapter_id']+canonical_url+title).encode()).hexdigest()
            blocked=[term for term in blocked_terms if term in title or term in canonical_url]
            c={'candidate_id':'auth-v45-'+dedupe[:16], 'adapter_id':adapter['adapter_id'], 'title':title, 'canonical_url':canonical_url, 'publisher':adapter['name'], 'query':q, 'rights_status':'unknown_pending_review', 'sensitivity':'metadata_only_review_required', 'dedupe_hash':dedupe, 'blocked_terms':blocked, 'public_auto_release':False, 'review_status':'candidate_needs_human_review'}
            candidates.append(c); count+=1
        runs.append({'run_id':run_id, 'adapter_id':adapter['adapter_id'], 'mode':'dry_run' if args.dry_run else 'scheduled_fetch', 'status':'dry_run_complete', 'candidate_count':count, 'deduped_count':0, 'blocked_count':0, 'rate_limit_per_minute':adapter.get('rate_limit_per_minute')})
    report={'version':'v45','dry_run':args.dry_run,'count':len(candidates),'runs':runs,'candidates':candidates,'public_auto_release':False}
    (ROOT/'data/integration/authority_source_fetch_dry_run_v45.generated.json').write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    lines=['-- generated by scripts/authority_source_fetch_worker_v45.py']
    for adapter in contract.get('adapters', []):
        state=json.dumps(adapter, ensure_ascii=False).replace("'", "''")
        lines.append(f"INSERT INTO authority_source_adapter_state_v45 (adapter_id, canonical_base_url, rate_limit_per_minute, last_status, state_json) VALUES ('{adapter['adapter_id']}', '{adapter['base_url']}', {int(adapter.get('rate_limit_per_minute',10))}, 'dry_run_complete', CAST('{state}' AS JSON)) ON DUPLICATE KEY UPDATE last_status=VALUES(last_status), state_json=VALUES(state_json);")
    for run in runs:
        rj=json.dumps(run, ensure_ascii=False).replace("'", "''")
        lines.append(f"INSERT INTO authority_source_worker_runs_v45 (run_id, adapter_id, mode, status, candidate_count, deduped_count, blocked_count, report_json) VALUES ('{run['run_id']}', '{run['adapter_id']}', '{run['mode']}', '{run['status']}', {run['candidate_count']}, {run['deduped_count']}, {run['blocked_count']}, CAST('{rj}' AS JSON)) ON DUPLICATE KEY UPDATE status=VALUES(status), report_json=VALUES(report_json);")
    for c in candidates:
        cj=json.dumps(c, ensure_ascii=False).replace("'", "''")
        title=c['title'].replace("'", "''")
        url=c['canonical_url'].replace("'", "''")
        publisher=c['publisher'].replace("'", "''")
        lines.append(f"INSERT INTO authority_source_candidates_v45 (candidate_id, adapter_id, canonical_url, title, publisher, rights_status, sensitivity, dedupe_hash, review_status, candidate_json) VALUES ('{c['candidate_id']}', '{c['adapter_id']}', '{url}', '{title}', '{publisher}', '{c['rights_status']}', '{c['sensitivity']}', '{c['dedupe_hash']}', '{c['review_status']}', CAST('{cj}' AS JSON)) ON DUPLICATE KEY UPDATE candidate_json=VALUES(candidate_json);")
    out=ROOT/'database/seeds/041_authority_source_worker_v45.generated.sql'
    out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f"authority source worker v45 OK: {len(candidates)} candidates, {len(runs)} runs")
if __name__=='__main__': main()
