#!/usr/bin/env python3
from __future__ import annotations
import json, html, hashlib
from pathlib import Path
ROOT=Path.cwd()
contract=json.loads((ROOT/'data/site/music_seo_og_contract_v45.json').read_text(encoding='utf-8'))
docs=json.loads((ROOT/'data/search/music_search_documents_v44.seed.json').read_text(encoding='utf-8')).get('documents', [])
base='https://pinuyumayan.tw'
urls=[f'{base}/music/search', f'{base}/tts-stt']+[f"{base}/music/{d['id']}" for d in docs[:80]]
xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join(f'  <url><loc>{html.escape(u)}</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>\n' for u in urls) + '</urlset>\n'
(ROOT/'data/site/sitemap_music_v45.generated.xml').write_text(xml, encoding='utf-8')
artifacts=[]
for d in docs[:80]:
    artifacts.append({'artifact_id':'seo-v45-'+hashlib.sha256(d['id'].encode()).hexdigest()[:16], 'route_path':f"/music/{d['id']}", 'artifact_type':'json_ld_music_metadata', 'artifact_json':{'@context':'https://schema.org','@type':'MusicRecording','name':d.get('title'),'description':d.get('summary') or d.get('body'),'inLanguage':'zh-Hant','isAccessibleForFree':True,'license':d.get('rights_status','metadata_only_review_required'),'publisher':{'@type':'Organization','name':'Pinuyumayan'}}, 'no_lyrics':True, 'no_audio_download':True})
report={'version':'v45','url_count':len(urls),'artifact_count':len(artifacts),'sitemap':'data/site/sitemap_music_v45.generated.xml','guard':contract.get('guard'), 'artifacts':artifacts[:20]}
(ROOT/'data/site/music_seo_og_report_v45.generated.json').write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
lines=['-- generated by scripts/build_site_seo_artifacts_v45.py']
for a in artifacts:
    aj=json.dumps(a['artifact_json'], ensure_ascii=False).replace("'", "''")
    lines.append(f"INSERT INTO main_site_seo_artifacts_v45 (artifact_id, route_path, artifact_type, artifact_json, no_lyrics, no_audio_download) VALUES ('{a['artifact_id']}', '{a['route_path']}', '{a['artifact_type']}', CAST('{aj}' AS JSON), TRUE, TRUE) ON DUPLICATE KEY UPDATE artifact_json=VALUES(artifact_json);")
out=ROOT/'database/seeds/041_site_seo_v45.generated.sql'
out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
print(f"site seo artifacts v45 OK: {len(urls)} sitemap URLs, {len(artifacts)} JSON-LD rows")
