#!/usr/bin/env python3
import argparse, json, re
from pathlib import Path

BLOCKED = ['卑南文化遺址','卑南遺址','卑南考古遺址','卑南文化公園','Peinan Site','Beinan Site','Peinan Archaeological Site']

def iter_json_items(path):
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding='utf-8'))
    if isinstance(data, list):
        return data
    return data.get('items') or data.get('cards') or data.get('documents') or []

def esc(s):
    return str(s or '').replace("'", "''")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='data/search/mysql_fulltext_seed_v28.generated.sql')
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()
    root = Path('.')
    sources = [
        ('knowledge_card', root/'data/content/public_source_grounded_cards_v21.json'),
        ('knowledge_card', root/'data/content/public_source_grounded_cards_v20.json'),
        ('search_document', root/'data/search/public_search_documents_v22.json'),
        ('search_document', root/'data/search/public_search_documents_v21.json'),
        ('pronunciation', root/'data/audio/puyuma_audio_playback_manifest_v17.json'),
    ]
    docs = []
    skipped = 0
    for source_type, path in sources:
        for idx, item in enumerate(iter_json_items(path)):
            title = item.get('title') or item.get('label') or item.get('form') or item.get('entry_id') or f'{source_type}-{idx}'
            body = item.get('body') or item.get('summary') or item.get('claim_text') or item.get('text') or json.dumps(item, ensure_ascii=False)
            blob = f'{title}\n{body}'
            if any(b in blob for b in BLOCKED):
                skipped += 1
                continue
            key = item.get('document_key') or item.get('card_id') or item.get('id') or f'v28-{source_type}-{idx}'
            docs.append((key, source_type, key, title, body))
    sql = ["-- generated by build_mysql_fulltext_index_v28.py", "TRUNCATE TABLE search_index_documents_v27;"]
    for key, st, sid, title, body in docs:
        sql.append(f"INSERT INTO search_index_documents_v27 (document_key, source_type, source_id, title, body_text, release_channel) VALUES ('{esc(key)}', 'knowledge_card', '{esc(sid)}', '{esc(title)}', '{esc(body)}', 'public') ON DUPLICATE KEY UPDATE title=VALUES(title), body_text=VALUES(body_text);")
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(sql)+'\n', encoding='utf-8')
    print(json.dumps({'version':'v28','output':str(out),'documents':len(docs),'skipped_forbidden':skipped,'dry_run':args.dry_run}, ensure_ascii=False, indent=2))

if __name__ == '__main__':
    main()
