#!/usr/bin/env python3
"""Rebuild data/database/review_queue_seed.json from verified facts and Puyuma corpus entries."""
from __future__ import annotations
import json
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / 'data' / 'database'

def main() -> None:
    facts = json.load(open(ROOT/'data/verified_pinuyumayan_facts.json', encoding='utf-8'))['facts']
    vocab = json.load(open(ROOT/'data/web/puyuma_vocabulary_audio_entries.json', encoding='utf-8'))['entries']
    tasks = []
    for f in facts:
        if f.get('sensitivity') in ('medium','high'):
            tasks.append({'task_id':f"review_fact_{f['id']}",'entity_type':'kb_fact','entity_id':f['id'],'priority':'high' if f.get('sensitivity')=='high' else 'normal','review_type':'cultural_sensitivity','status':'pending','autogenerated':True})
    for e in vocab:
        if e.get('tts',{}).get('review_required') or e.get('source',{}).get('license_review_required_before_commercial_use'):
            tasks.append({'task_id':f"review_vocab_{e['id']}",'entity_type':'puyuma_corpus_entry','entity_id':e['id'],'priority':'normal','review_type':'license_g2p_ipa_tts','status':'pending','autogenerated':True})
    out = {'version':'4.0.0','description':'Generated review queue seed','counts':dict(Counter(t['review_type'] for t in tasks)),'total':len(tasks),'tasks':tasks}
    DB.mkdir(parents=True, exist_ok=True)
    with open(DB/'review_queue_seed.json','w',encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(f"wrote {len(tasks)} review tasks")

if __name__ == '__main__':
    main()

