#!/usr/bin/env python3
from __future__ import annotations
import json, hashlib
from pathlib import Path
ROOT = Path.cwd()
syn = json.loads((ROOT/'data/search/music_query_synonyms_v45.json').read_text(encoding='utf-8'))
quality = json.loads((ROOT/'data/search/music_search_quality_v45.json').read_text(encoding='utf-8'))
docs = json.loads((ROOT/'data/search/music_search_documents_v44.seed.json').read_text(encoding='utf-8')).get('documents', [])

def expand(q: str):
    terms = [q]
    qlow = q.lower()
    for item in syn.get('items', []):
        if item['canonical'].lower() in qlow or any(a.lower() in qlow for a in item.get('aliases', [])):
            terms.append(item['canonical'])
            terms.extend(item.get('aliases', [])[:4])
    seen=[]
    for t in terms:
        if t and t not in seen:
            seen.append(t)
    return seen

def static_hits(q: str):
    expanded = expand(q)
    hits=[]
    for d in docs:
        text=json.dumps(d, ensure_ascii=False).lower()
        if any(t.lower() in text for t in expanded):
            hits.append(d['id'])
    return hits

results=[]
for i,test in enumerate(quality.get('quality_tests', []),1):
    hits=static_hits(test['query'])
    status='pass' if len(hits) >= test.get('min_hits_static',0) else 'review'
    results.append({**test, 'test_id': f'music-search-quality-v45-{i:03d}', 'expanded_terms': expand(test['query']), 'static_hit_count': len(hits), 'static_hit_ids': hits[:10], 'status': status})
report={'version':'v45','tests':results,'passed':sum(1 for r in results if r['status']=='pass'),'needs_review':sum(1 for r in results if r['status']!='pass'),'doc_count':len(docs)}
(ROOT/'data/search/music_search_quality_report_v45.generated.json').write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
lines=['-- generated by scripts/build_music_search_quality_v45.py']
for item in syn.get('items', []):
    canonical=item['canonical'].replace("'", "''")
    for alias in [item['canonical'], *item.get('aliases', [])]:
        a=alias.replace("'", "''")
        lines.append(f"INSERT INTO music_search_synonyms_v45 (canonical, alias, boost) VALUES ('{canonical}', '{a}', {float(item.get('boost',1.0)):.4f}) ON DUPLICATE KEY UPDATE boost=VALUES(boost);")
for r in results:
    test_json=json.dumps(r, ensure_ascii=False).replace("'", "''")
    q=r['query'].replace("'", "''")
    aliases=json.dumps(r.get('expected_alias_expansion',[]), ensure_ascii=False).replace("'", "''")
    lines.append(f"INSERT INTO music_search_quality_tests_v45 (test_id, query_text, expected_alias_json, min_hits_static, last_status, last_report_json) VALUES ('{r['test_id']}', '{q}', CAST('{aliases}' AS JSON), {int(r.get('min_hits_static',0))}, '{r['status']}', CAST('{test_json}' AS JSON)) ON DUPLICATE KEY UPDATE last_status=VALUES(last_status), last_report_json=VALUES(last_report_json);")
out=ROOT/'database/seeds/041_music_search_quality_v45.generated.sql'
out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
print(f"music search quality v45 OK: {report['passed']} passed, {report['needs_review']} needs review")
