#!/usr/bin/env python3
from __future__ import annotations
import json, hashlib
from pathlib import Path
ROOT = Path.cwd()
workflow = json.loads((ROOT/'data/audio/speech_review_workflow_v45.json').read_text(encoding='utf-8'))
out = ROOT/'database/seeds/041_speech_review_workflow_v45.generated.sql'
out.parent.mkdir(parents=True, exist_ok=True)
lines = ["-- generated by scripts/build_speech_review_workflow_seed_v45.py"]
for item in workflow.get('items', []):
    decision_id = item['workflow_id'] + '-pending'
    audit_id = 'audit-' + hashlib.sha256(decision_id.encode()).hexdigest()[:24]
    asset = item['asset_id'].replace("'", "''")
    reason = 'Initial v45 pending human review; all public release gates remain closed.'.replace("'", "''")
    decision_json = json.dumps(item, ensure_ascii=False).replace("'", "''")
    lines.append(f"INSERT INTO speech_review_decisions_v45 (decision_id, asset_id, reviewer_id, decision, gate_name, decision_reason, previous_status, next_status, decision_json) VALUES ('{decision_id}', '{asset}', 'system-v45', 'return_for_fix', 'all_gates', '{reason}', '{item.get('current_review_status','')}', 'pending_human_review', CAST('{decision_json}' AS JSON)) ON DUPLICATE KEY UPDATE decision_json=VALUES(decision_json);")
    lines.append(f"INSERT INTO speech_review_audit_log_v45 (audit_id, asset_id, actor_id, action, request_hash, before_json, after_json) VALUES ('{audit_id}', '{asset}', 'system-v45', 'seed_pending_review', '{hashlib.sha256(decision_json.encode()).hexdigest()}', NULL, CAST('{decision_json}' AS JSON)) ON DUPLICATE KEY UPDATE request_hash=VALUES(request_hash);")
out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
print(f"wrote {out} with {len(workflow.get('items', []))} review decisions")
