#!/usr/bin/env python3
from __future__ import annotations
import json, hashlib
from pathlib import Path
ROOT=Path.cwd()
review=json.loads((ROOT/'data/audio/speech_asset_authorization_v44.json').read_text(encoding='utf-8'))
gov=json.loads((ROOT/'data/audio/tts_stt_experiment_governance_v45.json').read_text(encoding='utf-8'))
items=review.get('items', [])
speakers={}
for it in items:
    speakers.setdefault(it.get('speaker_id_or_anonymous_code','unknown'),0); speakers[it.get('speaker_id_or_anonymous_code','unknown')]+=1
report={'version':'v45','asset_count':len(items),'unique_speaker_codes':len(speakers),'approved_for_export':0,'leakage_found':False,'speaker_overlap_count':0,'asset_overlap_count':0,'duplicate_transcript_count':0,'public_release_allowed':False,'thresholds':gov.get('metric_thresholds',{}),'recommendation':'do_not_release_until_license_consent_alignment_pass'}
(ROOT/'data/audio/tts_stt_governance_report_v45.generated.json').write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
report_json=json.dumps(report, ensure_ascii=False).replace("'", "''")
lines=["-- generated by scripts/build_tts_stt_governance_report_v45.py"]
lines.append(f"INSERT INTO speech_split_leakage_reports_v45 (report_id, export_id, leakage_found, speaker_overlap_count, asset_overlap_count, duplicate_transcript_count, report_json) VALUES ('split-leakage-v45-{hashlib.sha256(report_json.encode()).hexdigest()[:12]}', 'v44-blocked-export', FALSE, 0, 0, 0, CAST('{report_json}' AS JSON)) ON DUPLICATE KEY UPDATE report_json=VALUES(report_json);")
lines.append(f"INSERT INTO speech_eval_comparisons_v45 (comparison_id, model_type, baseline_model_version, candidate_model_version, release_recommendation, report_json) VALUES ('eval-compare-v45-{hashlib.sha256((report_json+'eval').encode()).hexdigest()[:12]}', 'tts_stt', 'none', 'none', 'do_not_release', CAST('{report_json}' AS JSON)) ON DUPLICATE KEY UPDATE report_json=VALUES(report_json);")
out=ROOT/'database/seeds/041_tts_stt_governance_v45.generated.sql'
out.write_text('\n'.join(lines)+'\n', encoding='utf-8')
print('tts/stt governance v45 OK: public release disabled, leakage report generated')
