#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/production_release_certificate_v54.json", "data/security/legal_speech_dataset_release_v54.json", "data/search/music_search_ranking_rollout_v54.json", "data/integration/authority_metadata_site_publication_v54.json", "data/audio/speech_model_governance_archive_v54.json", "data/site/operations_monitoring_automation_v54.json", "data/admin/music_speech_review_center_v54.json", "data/ops/vps_preflight_v54.json", "data/development/next_upgrade_plan_v55.json", "backend/src/rest/ttsSttMusicV54Routes.ts", "frontend-sdk/ttsSttMusicClient.v54.ts", "webapp/components/MusicSpeechReviewCenterV54.tsx", "webapp/app/admin/music-speech/v54/page.tsx", "database/migrations/0050_tts_stt_music_v54.sql", "database/seeds/050_tts_stt_music_v54.sql", "database/seeds/050_production_release_certificate_v54.generated.sql", "database/seeds/050_legal_speech_dataset_release_v54.generated.sql", "database/seeds/050_search_ranking_rollout_v54.generated.sql", "database/seeds/050_authority_site_publication_v54.generated.sql", "database/seeds/050_model_governance_archive_v54.generated.sql", "database/seeds/050_operations_monitoring_automation_v54.generated.sql", "deploy/vps-tts-stt-v54.sh", "docs/tts_stt_music_v54.md", "docs/model_governance_archive_v54.generated.md", "docs/production_release_certificate_v54.generated.md", "docs/next_upgrade_plan_v55.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v54 files: '+', '.join(missing))
release=json.loads((root/'data/deployment/production_release_certificate_v54.json').read_text(encoding='utf-8'))
if len(release.get('checks',[])) < 6 or release.get('summary',{}).get('production_release_allowed') is not False: raise SystemExit('v54 release certificate invalid')
legal=json.loads((root/'data/security/legal_speech_dataset_release_v54.json').read_text(encoding='utf-8'))
if len(legal.get('assets',[])) != 20 or legal.get('summary',{}).get('dataset_export_allowed') is not False or legal.get('summary',{}).get('train_rows') != 0: raise SystemExit('v54 legal dataset invalid')
search=json.loads((root/'data/search/music_search_ranking_rollout_v54.json').read_text(encoding='utf-8'))
if len(search.get('features',[])) < 3 or search.get('summary',{}).get('rollout_100_allowed') is not False: raise SystemExit('v54 search rollout invalid')
auth=json.loads((root/'data/integration/authority_metadata_site_publication_v54.json').read_text(encoding='utf-8'))
if len(auth.get('publication_cards',[])) < 3 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_lyrics_allowed') is not False: raise SystemExit('v54 authority publication invalid')
model=json.loads((root/'data/audio/speech_model_governance_archive_v54.json').read_text(encoding='utf-8'))
if model.get('summary',{}).get('public_model_release_allowed') is not False or len(model.get('sections',[])) < 6: raise SystemExit('v54 model archive invalid')
site=json.loads((root/'data/site/operations_monitoring_automation_v54.json').read_text(encoding='utf-8'))
if site.get('summary',{}).get('minimum_contrast') != 'WCAG AA' or len(site.get('routes',[])) < 7: raise SystemExit('v54 site ops invalid')
migration=(root/'database/migrations/0050_tts_stt_music_v54.sql').read_text(encoding='utf-8')
for table in ["production_release_signoffs_v54", "production_release_evidence_v54", "production_release_certificates_v54", "production_release_reopen_v54", "legal_speech_evidence_uploads_v54", "legal_speech_native_reviews_v54", "legal_speech_dataset_asset_approvals_v54", "legal_speech_dataset_versions_v54", "legal_speech_dataset_exports_v54", "music_search_rollout_metrics_v54", "music_search_rollout_50_v54", "music_search_rollout_100_v54", "music_search_ranking_rollbacks_v54", "authority_site_cards_v54", "authority_metadata_index_jobs_v54", "authority_sitemap_og_pings_v54", "authority_source_drift_events_v54", "authority_takedown_executions_v54", "speech_model_pdf_archives_v54", "speech_model_lineage_archives_v54", "speech_model_final_signoffs_v54", "speech_model_governance_seals_v54", "site_uptime_cwv_samples_v54", "site_og_sitemap_checks_v54", "site_daily_ops_reports_v54", "site_weekly_ops_reports_v54", "site_alerts_v54"]:
    if table not in migration: raise SystemExit(f'v54 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV54Routes.ts').read_text(encoding='utf-8')
for snippet in ["record-release-signoff", "attach-cutover-evidence", "approve-production-certificate", "reopen-release-certificate", "upload-legal-evidence", "record-native-review", "approve-dataset-asset", "build-dataset-version", "export-train-dev-test", "record-rollout-metric", "promote-rollout-50", "promote-rollout-100", "rollback-ranking-feature", "publish-site-card", "index-metadata-card", "ping-sitemap-og", "record-source-drift", "execute-takedown", "archive-governance-pdf", "archive-lineage-dag", "record-final-signoff", "seal-model-governance", "record-uptime-cwv", "record-og-sitemap-check", "create-daily-ops-report", "create-weekly-ops-report", "send-alert", "beginTransaction", "rollback()", "commit()"]:
    if snippet not in route: raise SystemExit(f'v54 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV54Routes' not in server: raise SystemExit('server not registering v54 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v54/review-center", "/api/ops/vps/v54/release-certificate", "/api/admin/speech-training/v54/dataset-release", "/api/ops/search/music/v54/ranking-rollout", "/api/public/music/metadata/v54/cards", "/api/ops/authority-sources/v54/site-publication", "/api/ops/speech-training/v54/governance-archive", "/api/ops/site/v54/operations-automation", "/api/ops/vps/v54/preflight-contract", "/api/ops/next-upgrade-plan/v55", "/api/internal/vps/v54/record-release-signoff", "/api/internal/vps/v54/attach-cutover-evidence", "/api/internal/vps/v54/approve-production-certificate", "/api/internal/vps/v54/reopen-release-certificate", "/api/internal/speech-training/v54/upload-legal-evidence", "/api/internal/speech-training/v54/record-native-review", "/api/internal/speech-training/v54/approve-dataset-asset", "/api/internal/speech-training/v54/build-dataset-version", "/api/internal/speech-training/v54/export-train-dev-test", "/api/internal/search/music/v54/record-rollout-metric", "/api/internal/search/music/v54/promote-rollout-50", "/api/internal/search/music/v54/promote-rollout-100", "/api/internal/search/music/v54/rollback-ranking-feature", "/api/internal/authority-sources/v54/publish-site-card", "/api/internal/authority-sources/v54/index-metadata-card", "/api/internal/authority-sources/v54/ping-sitemap-og", "/api/internal/authority-sources/v54/record-source-drift", "/api/internal/authority-sources/v54/execute-takedown", "/api/internal/speech-training/v54/archive-governance-pdf", "/api/internal/speech-training/v54/archive-lineage-dag", "/api/internal/speech-training/v54/record-final-signoff", "/api/internal/speech-training/v54/seal-model-governance", "/api/internal/site/v54/record-uptime-cwv", "/api/internal/site/v54/record-og-sitemap-check", "/api/internal/site/v54/create-daily-ops-report", "/api/internal/site/v54/create-weekly-ops-report", "/api/internal/site/v54/send-alert"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 626: raise SystemExit('OpenAPI path count did not increase enough for v54')
plan=json.loads((root/'data/development/next_upgrade_plan_v55.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v55 plan must include 6 items')
print(f"tts/stt music v54 OK: {len(legal.get('assets',[]))} dataset assets, {len(release.get('checks',[]))} release checks, {len(search.get('features',[]))} rollout features, {len(auth.get('publication_cards',[]))} metadata cards, {len(site.get('routes',[]))} monitored routes, {len(api.get('paths',{}))} OpenAPI paths")
