#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/release_evidence_ledger_seal_v57.json", "data/security/legal_speech_train_dev_test_v57.json", "data/search/music_search_2472_decision_v57.json", "data/integration/authority_metadata_evidence_archive_v57.json", "data/audio/speech_model_governance_audit_query_v57.json", "data/site/operations_report_notifications_v57.json", "data/admin/music_speech_review_center_v57.json", "data/ops/vps_preflight_v57.json", "data/development/next_upgrade_plan_v58.json", "backend/src/rest/ttsSttMusicV57Routes.ts", "frontend-sdk/ttsSttMusicClient.v57.ts", "webapp/components/MusicSpeechReviewCenterV57.tsx", "webapp/app/admin/music-speech/v57/page.tsx", "database/migrations/0053_tts_stt_music_v57.sql", "database/seeds/053_tts_stt_music_v57.sql", "database/seeds/053_production_release_ledger_v57.generated.sql", "database/seeds/053_legal_speech_train_dev_test_v57.generated.sql", "database/seeds/053_search_2472_decision_v57.generated.sql", "database/seeds/053_authority_metadata_evidence_v57.generated.sql", "database/seeds/053_governance_audit_query_v57.generated.sql", "database/seeds/053_operations_notifications_v57.generated.sql", "deploy/vps-tts-stt-v57.sh", "docs/tts_stt_music_v57.md", "docs/legal_speech_train_dev_test_v57.generated.md", "docs/release_evidence_ledger_seal_v57.generated.md", "docs/operations_report_notifications_v57.generated.md", "docs/next_upgrade_plan_v58.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v57 files: '+', '.join(missing))
release=json.loads((root/'data/deployment/release_evidence_ledger_seal_v57.json').read_text(encoding='utf-8'))
if len(release.get('checks',[])) < 6 or release.get('summary',{}).get('production_release_certified') is not False: raise SystemExit('v57 release ledger invalid')
legal=json.loads((root/'data/security/legal_speech_train_dev_test_v57.json').read_text(encoding='utf-8'))
if len(legal.get('assets',[])) != 20 or legal.get('summary',{}).get('dataset_export_allowed') is not False or legal.get('summary',{}).get('train_rows') != 0: raise SystemExit('v57 legal train/dev/test invalid')
search=json.loads((root/'data/search/music_search_2472_decision_v57.json').read_text(encoding='utf-8'))
if len(search.get('decisions',[])) < 3 or search.get('summary',{}).get('rollback_ready') is not True: raise SystemExit('v57 search decision invalid')
auth=json.loads((root/'data/integration/authority_metadata_evidence_archive_v57.json').read_text(encoding='utf-8'))
if len(auth.get('publication_evidence',[])) < 3 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_lyrics_allowed') is not False: raise SystemExit('v57 authority evidence invalid')
model=json.loads((root/'data/audio/speech_model_governance_audit_query_v57.json').read_text(encoding='utf-8'))
if len(model.get('artifacts',[])) < 6 or model.get('summary',{}).get('public_model_release_allowed') is not False: raise SystemExit('v57 governance audit invalid')
site=json.loads((root/'data/site/operations_report_notifications_v57.json').read_text(encoding='utf-8'))
if site.get('summary',{}).get('minimum_contrast') != 'WCAG AA' or len(site.get('report_jobs',[])) < 6: raise SystemExit('v57 operations notifications invalid')
migration=(root/'database/migrations/0053_tts_stt_music_v57.sql').read_text(encoding='utf-8')
for table in ["release_evidence_ledger_entries_v57", "release_evidence_certificate_seals_v57", "release_evidence_backup_restore_records_v57", "release_evidence_observation_samples_v57", "legal_speech_dataset_exports_v57", "legal_speech_checksum_manifests_v57", "legal_speech_blocked_reports_v57", "legal_speech_model_cards_v57", "music_search_monitoring_decisions_v57", "music_search_anomaly_tasks_v57", "music_search_rollback_decisions_v57", "authority_metadata_public_evidence_v57", "authority_metadata_citation_screenshots_v57", "authority_metadata_takedown_rehearsals_v57", "speech_governance_artifact_downloads_v57", "speech_governance_audit_exports_v57", "speech_governance_permission_checks_v57", "site_ops_report_deliveries_v57", "site_ops_notification_channels_v57", "site_ops_alert_acknowledgements_v57", "site_ops_weekly_summaries_v57"]:
    if table not in migration: raise SystemExit(f'v57 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV57Routes.ts').read_text(encoding='utf-8')
for snippet in ["ingest-release-evidence", "seal-release-certificate", "record-backup-restore-result", "record-30m-observation", "export-train-dev-test", "write-checksum-manifest", "write-blocked-report", "write-model-card", "record-24h-decision", "record-72h-decision", "create-anomaly-task", "execute-rollout-rollback", "archive-publication-evidence", "store-citation-screenshot", "store-source-drift-sample", "store-takedown-rehearsal", "download-governance-artifact", "export-audit-log", "check-download-permission", "send-daily-report", "send-weekly-report", "register-notification-channel", "acknowledge-alert", "beginTransaction", "rollback()", "commit()"]:
    if snippet not in route: raise SystemExit(f'v57 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV57Routes' not in server: raise SystemExit('server not registering v57 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v57/review-center", "/api/ops/vps/v57/release-evidence-ledger-seal", "/api/admin/speech-training/v57/legal-train-dev-test", "/api/ops/search/music/v57/2472-decision", "/api/public/music/metadata/v57/evidence-archive", "/api/ops/authority-sources/v57/evidence-archive", "/api/ops/speech-training/v57/governance-audit-query", "/api/ops/site/v57/report-notifications", "/api/ops/vps/v57/preflight-contract", "/api/ops/next-upgrade-plan/v58", "/api/internal/vps/v57/ingest-release-evidence", "/api/internal/vps/v57/seal-release-certificate", "/api/internal/vps/v57/record-backup-restore-result", "/api/internal/vps/v57/record-30m-observation", "/api/internal/speech-training/v57/export-train-dev-test", "/api/internal/speech-training/v57/write-checksum-manifest", "/api/internal/speech-training/v57/write-blocked-report", "/api/internal/speech-training/v57/write-model-card", "/api/internal/search/music/v57/record-24h-decision", "/api/internal/search/music/v57/record-72h-decision", "/api/internal/search/music/v57/create-anomaly-task", "/api/internal/search/music/v57/execute-rollout-rollback", "/api/internal/authority-sources/v57/archive-publication-evidence", "/api/internal/authority-sources/v57/store-citation-screenshot", "/api/internal/authority-sources/v57/store-source-drift-sample", "/api/internal/authority-sources/v57/store-takedown-rehearsal", "/api/internal/speech-training/v57/download-governance-artifact", "/api/internal/speech-training/v57/export-audit-log", "/api/internal/speech-training/v57/check-download-permission", "/api/internal/site/v57/send-daily-report", "/api/internal/site/v57/send-weekly-report", "/api/internal/site/v57/register-notification-channel", "/api/internal/site/v57/acknowledge-alert"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 723: raise SystemExit('OpenAPI path count did not increase enough for v57')
plan=json.loads((root/'data/development/next_upgrade_plan_v58.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v58 plan must include 6 items')
print(f"tts/stt music v57 OK: {len(legal.get('assets',[]))} legal candidates, {len(release.get('checks',[]))} ledger checks, {len(search.get('decisions',[]))} search decisions, {len(auth.get('publication_evidence',[]))} metadata evidence records, {len(site.get('report_jobs',[]))} report jobs, {len(api.get('paths',{}))} OpenAPI paths")
