#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=['data/deployment/production_evidence_backfill_v53.json', 'data/security/legal_speech_training_batch_v53.json', 'data/search/music_search_ranking_upgrade_v53.json', 'data/integration/authority_metadata_publication_v53.json', 'data/audio/speech_model_governance_seal_v53.json', 'data/site/formal_monitoring_operations_v53.json', 'data/admin/music_speech_review_center_v53.json', 'data/ops/vps_preflight_v53.json', 'data/development/next_upgrade_plan_v54.json', 'backend/src/rest/ttsSttMusicV53Routes.ts', 'frontend-sdk/ttsSttMusicClient.v53.ts', 'webapp/components/MusicSpeechReviewCenterV53.tsx', 'webapp/app/admin/music-speech/v53/page.tsx', 'database/migrations/0049_tts_stt_music_v53.sql', 'database/seeds/049_tts_stt_music_v53.sql', 'database/seeds/049_production_evidence_backfill_v53.generated.sql', 'database/seeds/049_legal_speech_training_batch_v53.generated.sql', 'database/seeds/049_search_ranking_upgrade_v53.generated.sql', 'database/seeds/049_authority_metadata_publication_v53.generated.sql', 'database/seeds/049_model_governance_seal_v53.generated.sql', 'database/seeds/049_formal_monitoring_operations_v53.generated.sql', 'deploy/vps-tts-stt-v53.sh', 'docs/tts_stt_music_v53.md', 'docs/model_governance_seal_v53.generated.md', 'docs/next_upgrade_plan_v54.md']
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v53 files: '+', '.join(missing))
backfill=json.loads((root/'data/deployment/production_evidence_backfill_v53.json').read_text(encoding='utf-8'))
if len(backfill.get('checks',[])) < 6 or backfill.get('summary',{}).get('release_allowed_without_real_evidence') is not False: raise SystemExit('v53 backfill invalid')
legal=json.loads((root/'data/security/legal_speech_training_batch_v53.json').read_text(encoding='utf-8'))
if len(legal.get('candidates',[])) != 20 or legal.get('summary',{}).get('approved_assets') != 0 or legal.get('summary',{}).get('export_allowed') is not False: raise SystemExit('v53 legal batch invalid')
search=json.loads((root/'data/search/music_search_ranking_upgrade_v53.json').read_text(encoding='utf-8'))
if len(search.get('ranking_decisions',[])) < 3 or search.get('summary',{}).get('default_rollout_allowed') is not False: raise SystemExit('v53 search ranking invalid')
auth=json.loads((root/'data/integration/authority_metadata_publication_v53.json').read_text(encoding='utf-8'))
if len(auth.get('publication_cards',[])) < 3 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_lyrics_allowed') is not False: raise SystemExit('v53 authority publication invalid')
model=json.loads((root/'data/audio/speech_model_governance_seal_v53.json').read_text(encoding='utf-8'))
if model.get('summary',{}).get('public_model_release_allowed') is not False or len(model.get('signoff_sections',[])) < 4: raise SystemExit('v53 model seal invalid')
site=json.loads((root/'data/site/formal_monitoring_operations_v53.json').read_text(encoding='utf-8'))
if site.get('summary',{}).get('minimum_contrast') != 'WCAG AA' or len(site.get('routes',[])) < 7: raise SystemExit('v53 formal monitoring invalid')
migration=(root/'database/migrations/0049_tts_stt_music_v53.sql').read_text(encoding='utf-8')
for table in ['production_evidence_backfill_checks_v53','production_evidence_dns_records_v53','production_evidence_backup_restore_v53','production_evidence_observation_windows_v53','production_backfill_seals_v53','legal_speech_evidence_files_v53','legal_speech_asset_approvals_v53','legal_speech_exports_v53','music_search_ranking_metrics_v53','music_search_ranking_rollouts_v53','music_search_synonym_merge_tasks_v53','authority_metadata_public_cards_v53','authority_metadata_source_changes_v53','authority_metadata_takedown_tests_v53','speech_model_governance_pdfs_v53','speech_model_signoff_sections_v53','speech_model_release_blockers_v53','site_uptime_samples_v53','site_error_rate_samples_v53','site_ops_reports_v53','site_alert_notifications_v53']:
    if table not in migration: raise SystemExit(f'v53 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV53Routes.ts').read_text(encoding='utf-8')
for snippet in ['record-health-evidence','record-dns-evidence','record-backup-restore-evidence','record-observation-window','seal-backfill-report','attach-evidence-file','approve-legal-asset','export-legal-batch','record-native-speaker-review','record-ranking-metric','approve-ranking-rollout','rollback-ranking-rollout','create-synonym-merge-task','publish-metadata-card','record-source-change','test-takedown-flow','render-governance-pdf','record-signoff-section','record-lineage-dag','close-release-blocker','record-uptime-sample','record-error-rate','record-lighthouse-run','create-ops-report','send-alert-notification','beginTransaction','rollback()','commit()']:
    if snippet not in route: raise SystemExit(f'v53 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV53Routes' not in server: raise SystemExit('server not registering v53 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ['/api/admin/music-speech/v53/review-center','/api/ops/vps/v53/evidence-backfill','/api/internal/vps/v53/record-health-evidence','/api/internal/vps/v53/record-dns-evidence','/api/internal/vps/v53/record-backup-restore-evidence','/api/internal/vps/v53/record-observation-window','/api/internal/vps/v53/seal-backfill-report','/api/admin/speech-training/v53/legal-batch','/api/internal/speech-training/v53/attach-evidence-file','/api/internal/speech-training/v53/approve-legal-asset','/api/internal/speech-training/v53/export-legal-batch','/api/internal/speech-training/v53/record-native-speaker-review','/api/ops/search/music/v53/ranking-upgrade','/api/internal/search/music/v53/record-ranking-metric','/api/internal/search/music/v53/approve-ranking-rollout','/api/internal/search/music/v53/rollback-ranking-rollout','/api/internal/search/music/v53/create-synonym-merge-task','/api/public/music/metadata/v53/cards','/api/ops/authority-sources/v53/publication','/api/internal/authority-sources/v53/publish-metadata-card','/api/internal/authority-sources/v53/record-source-change','/api/internal/authority-sources/v53/test-takedown-flow','/api/ops/speech-training/v53/model-seal','/api/internal/speech-training/v53/render-governance-pdf','/api/internal/speech-training/v53/record-signoff-section','/api/internal/speech-training/v53/record-lineage-dag','/api/internal/speech-training/v53/close-release-blocker','/api/ops/site/v53/formal-monitoring','/api/internal/site/v53/record-uptime-sample','/api/internal/site/v53/record-error-rate','/api/internal/site/v53/record-lighthouse-run','/api/internal/site/v53/create-ops-report','/api/internal/site/v53/send-alert-notification','/api/ops/vps/v53/preflight-contract','/api/ops/next-upgrade-plan/v54']:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 589: raise SystemExit('OpenAPI path count did not increase enough for v53')
plan=json.loads((root/'data/development/next_upgrade_plan_v54.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v54 plan must include 6 items')
print(f"tts/stt music v53 OK: {len(legal.get('candidates',[]))} legal candidates, {len(backfill.get('checks',[]))} evidence checks, {len(search.get('ranking_decisions',[]))} ranking decisions, {len(auth.get('publication_cards',[]))} metadata cards, {len(site.get('routes',[]))} monitored routes, {len(api.get('paths',{}))} OpenAPI paths")
