#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/release_certificate_postseal_validation_v59.json", "data/security/legal_speech_dataset_v58_freeze_v59.json", "data/search/music_search_production_policy_v59.json", "data/integration/authority_metadata_publication_expansion_v59.json", "data/audio/speech_governance_download_audit_hardening_v59.json", "data/site/operations_notification_closed_loop_v59.json", "data/admin/music_speech_review_center_v59.json", "data/ops/vps_preflight_v59.json", "data/development/next_upgrade_plan_v60.json", "backend/src/rest/ttsSttMusicV59Routes.ts", "frontend-sdk/ttsSttMusicClient.v59.ts", "webapp/components/MusicSpeechReviewCenterV59.tsx", "webapp/app/admin/music-speech/v59/page.tsx", "database/migrations/0055_tts_stt_music_v59.sql", "database/seeds/055_tts_stt_music_v59.sql", "database/seeds/055_production_postseal_validation_v59.generated.sql", "database/seeds/055_legal_speech_dataset_freeze_v59.generated.sql", "database/seeds/055_search_production_policy_v59.generated.sql", "database/seeds/055_authority_metadata_expansion_v59.generated.sql", "database/seeds/055_governance_download_hardening_v59.generated.sql", "database/seeds/055_operations_closed_loop_v59.generated.sql", "deploy/vps-tts-stt-v59.sh", "docs/tts_stt_music_v59.md", "docs/release_certificate_postseal_validation_v59.generated.md", "docs/legal_speech_dataset_v58_freeze_v59.generated.md", "docs/operations_notification_closed_loop_v59.generated.md", "docs/next_upgrade_plan_v60.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v59 files: '+', '.join(missing))
release=json.loads((root/'data/deployment/release_certificate_postseal_validation_v59.json').read_text(encoding='utf-8'))
if len(release.get('checks',[])) < 6 or release.get('summary',{}).get('release_certificate_finally_sealed') is not False: raise SystemExit('v59 postseal validation invalid')
dataset=json.loads((root/'data/security/legal_speech_dataset_v58_freeze_v59.json').read_text(encoding='utf-8'))
if len(dataset.get('assets',[])) != 20 or dataset.get('summary',{}).get('dataset_frozen') is not False or dataset.get('summary',{}).get('train_rows') != 0: raise SystemExit('v59 dataset freeze gate invalid')
search=json.loads((root/'data/search/music_search_production_policy_v59.json').read_text(encoding='utf-8'))
if len(search.get('features',[])) < 3 or search.get('summary',{}).get('rollback_drill_ready') is not True: raise SystemExit('v59 search production policy invalid')
auth=json.loads((root/'data/integration/authority_metadata_publication_expansion_v59.json').read_text(encoding='utf-8'))
if len(auth.get('records',[])) < 6 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_full_lyrics_allowed') is not False: raise SystemExit('v59 authority expansion invalid')
gov=json.loads((root/'data/audio/speech_governance_download_audit_hardening_v59.json').read_text(encoding='utf-8'))
if len(gov.get('artifacts',[])) < 6 or gov.get('summary',{}).get('abnormal_download_alert_ready') is not True: raise SystemExit('v59 governance hardening invalid')
ops=json.loads((root/'data/site/operations_notification_closed_loop_v59.json').read_text(encoding='utf-8'))
if len(ops.get('jobs',[])) < 6 or ops.get('summary',{}).get('ack_enabled') is not True or ops.get('summary',{}).get('real_delivery_verified') is not False: raise SystemExit('v59 operations closed loop invalid')
migration=(root/'database/migrations/0055_tts_stt_music_v59.sql').read_text(encoding='utf-8')
for table in ["release_certificate_postseal_validations_v59", "release_restore_audit_samples_v59", "release_rollback_audit_samples_v59", "release_dns_cloudflare_audit_samples_v59", "release_observation_audit_samples_v59", "release_hash_chain_audit_samples_v59", "legal_speech_dataset_freezes_v59", "legal_speech_train_dev_test_exports_v59", "legal_speech_checksum_manifests_v59", "legal_speech_model_cards_v59", "legal_speech_blocked_reports_v59", "search_production_policies_v59", "search_quality_weekly_reports_v59", "search_anomaly_sla_tasks_v59", "search_rollback_drills_v59", "authority_metadata_publication_expansions_v59", "authority_citation_screenshot_evidence_v59", "authority_takedown_rehearsals_v59", "authority_source_drift_audits_v59", "governance_download_watermark_verifications_v59", "governance_abnormal_download_alerts_v59", "governance_rbac_test_reports_v59", "governance_audit_export_signoffs_v59", "operations_notification_acks_v59", "operations_notification_escalations_v59", "operations_notification_closures_v59", "operations_weekly_retrospectives_v59", "operations_improvement_tasks_v59"]:
    if table not in migration: raise SystemExit(f'v59 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV59Routes.ts').read_text(encoding='utf-8')
for snippet in ["record-postseal-validation", "record-restore-audit-sample", "record-rollback-audit-sample", "record-dns-cloudflare-audit-sample", "record-observation-audit-sample", "record-hash-chain-audit-sample", "freeze-dataset", "export-train-dev-test", "write-checksum-manifest", "write-model-card", "write-blocked-report", "apply-production-policy", "write-weekly-report", "create-anomaly-sla-task", "record-rollback-drill", "record-publication-expansion", "record-citation-screenshot", "record-takedown-rehearsal", "record-source-drift-audit", "verify-download-watermark", "record-abnormal-download-alert", "write-rbac-test-report", "sign-audit-export", "ack-notification", "escalate-notification", "close-notification", "write-weekly-retrospective", "create-improvement-task", "beginTransaction", "rollback", "commit"]:
    if snippet not in route: raise SystemExit(f'v59 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV59Routes' not in server: raise SystemExit('server not registering v59 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v59/review-center", "/api/ops/vps/v59/postseal-validation", "/api/admin/speech-training/v59/dataset-freeze", "/api/ops/search/music/v59/production-policy", "/api/ops/authority-sources/v59/publication-expansion", "/api/ops/speech-training/v59/governance-download-hardening", "/api/ops/site/v59/notification-closed-loop", "/api/ops/vps/v59/preflight-contract", "/api/ops/next-upgrade-plan/v60", "/api/internal/vps/v59/record-postseal-validation", "/api/internal/vps/v59/record-restore-audit-sample", "/api/internal/vps/v59/record-rollback-audit-sample", "/api/internal/vps/v59/record-dns-cloudflare-audit-sample", "/api/internal/vps/v59/record-observation-audit-sample", "/api/internal/vps/v59/record-hash-chain-audit-sample", "/api/internal/speech-training/v59/freeze-dataset", "/api/internal/speech-training/v59/export-train-dev-test", "/api/internal/speech-training/v59/write-checksum-manifest", "/api/internal/speech-training/v59/write-model-card", "/api/internal/speech-training/v59/write-blocked-report", "/api/internal/search/music/v59/apply-production-policy", "/api/internal/search/music/v59/write-weekly-report", "/api/internal/search/music/v59/create-anomaly-sla-task", "/api/internal/search/music/v59/record-rollback-drill", "/api/internal/authority/v59/record-publication-expansion", "/api/internal/authority/v59/record-citation-screenshot", "/api/internal/authority/v59/record-takedown-rehearsal", "/api/internal/authority/v59/record-source-drift-audit", "/api/internal/governance/v59/verify-download-watermark", "/api/internal/governance/v59/record-abnormal-download-alert", "/api/internal/governance/v59/write-rbac-test-report", "/api/internal/governance/v59/sign-audit-export", "/api/internal/ops/v59/ack-notification", "/api/internal/ops/v59/escalate-notification", "/api/internal/ops/v59/close-notification", "/api/internal/ops/v59/write-weekly-retrospective", "/api/internal/ops/v59/create-improvement-task"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 791: raise SystemExit('OpenAPI path count did not increase enough for v59')
plan=json.loads((root/'data/development/next_upgrade_plan_v60.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v60 plan must include 6 items')
print(f"tts/stt music v59 OK: {len(dataset.get('assets',[]))} dataset candidates, {len(release.get('checks',[]))} postseal checks, {len(search.get('features',[]))} search features, {len(auth.get('records',[]))} metadata records, {len(ops.get('jobs',[]))} closed-loop jobs, {len(api.get('paths',{}))} OpenAPI paths")
