#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/production_release_certificate_signed_v55.json", "data/security/legal_speech_unblocked_dataset_v55.json", "data/search/music_search_100_rollout_v55.json", "data/integration/authority_metadata_publish_takedown_v55.json", "data/audio/speech_model_governance_archive_center_v55.json", "data/site/operations_monitoring_sop_v55.json", "data/admin/music_speech_review_center_v55.json", "data/ops/vps_preflight_v55.json", "data/development/next_upgrade_plan_v56.json", "backend/src/rest/ttsSttMusicV55Routes.ts", "frontend-sdk/ttsSttMusicClient.v55.ts", "webapp/components/MusicSpeechReviewCenterV55.tsx", "webapp/app/admin/music-speech/v55/page.tsx", "database/migrations/0051_tts_stt_music_v55.sql", "database/seeds/051_tts_stt_music_v55.sql", "database/seeds/051_production_release_signed_certificate_v55.generated.sql", "database/seeds/051_legal_speech_unblocked_dataset_v55.generated.sql", "database/seeds/051_search_rollout_100_v55.generated.sql", "database/seeds/051_authority_publish_takedown_v55.generated.sql", "database/seeds/051_model_governance_center_v55.generated.sql", "database/seeds/051_operations_sop_v55.generated.sql", "deploy/vps-tts-stt-v55.sh", "docs/tts_stt_music_v55.md", "docs/model_governance_center_v55.generated.md", "docs/production_release_certificate_signed_v55.generated.md", "docs/next_upgrade_plan_v56.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v55 files: '+', '.join(missing))
cert=json.loads((root/'data/deployment/production_release_certificate_signed_v55.json').read_text(encoding='utf-8'))
if len(cert.get('checks',[])) < 6 or cert.get('summary',{}).get('production_release_allowed') is not False or cert.get('summary',{}).get('release_certificate_signed') is not False: raise SystemExit('v55 signed certificate package invalid')
legal=json.loads((root/'data/security/legal_speech_unblocked_dataset_v55.json').read_text(encoding='utf-8'))
if len(legal.get('assets',[])) != 20 or legal.get('summary',{}).get('dataset_export_allowed') is not False or legal.get('summary',{}).get('train_rows') != 0: raise SystemExit('v55 legal dataset package invalid')
search=json.loads((root/'data/search/music_search_100_rollout_v55.json').read_text(encoding='utf-8'))
if len(search.get('features',[])) < 3 or search.get('summary',{}).get('rollout_100_allowed') is not False: raise SystemExit('v55 search rollout invalid')
auth=json.loads((root/'data/integration/authority_metadata_publish_takedown_v55.json').read_text(encoding='utf-8'))
if len(auth.get('publication_cards',[])) < 3 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_lyrics_allowed') is not False: raise SystemExit('v55 authority publication invalid')
model=json.loads((root/'data/audio/speech_model_governance_archive_center_v55.json').read_text(encoding='utf-8'))
if model.get('summary',{}).get('public_model_release_allowed') is not False or len(model.get('sections',[])) < 6: raise SystemExit('v55 model center invalid')
site=json.loads((root/'data/site/operations_monitoring_sop_v55.json').read_text(encoding='utf-8'))
if site.get('summary',{}).get('minimum_contrast') != 'WCAG AA' or len(site.get('monitors',[])) < 7: raise SystemExit('v55 ops SOP invalid')
migration=(root/'database/migrations/0051_tts_stt_music_v55.sql').read_text(encoding='utf-8')
for table in ["production_release_signed_certificates_v55", "production_release_signed_evidence_v55", "production_release_signed_pdf_artifacts_v55", "production_release_signed_reopen_v55", "legal_speech_real_evidence_files_v55", "legal_speech_hash_chain_seals_v55", "legal_speech_unblock_decisions_v55", "legal_speech_dataset_split_exports_v55", "music_search_rollout_100_decisions_v55", "music_search_rollout_100_metrics_v55", "music_search_rollout_100_rollbacks_v55", "authority_metadata_public_cards_v55", "authority_metadata_takedown_rehearsals_v55", "authority_metadata_source_drift_v55", "speech_model_governance_center_artifacts_v55", "speech_model_governance_audit_downloads_v55", "speech_model_governance_blocker_closure_v55", "site_ops_daily_reports_v55", "site_ops_weekly_reports_v55", "site_ops_alert_routes_v55", "site_ops_live_monitor_samples_v55"]:
    if table not in migration: raise SystemExit(f'v55 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV55Routes.ts').read_text(encoding='utf-8')
for snippet in ["sign-release-certificate", "attach-signed-evidence", "archive-certificate-pdf", "reopen-signed-certificate", "upload-real-evidence-file", "seal-asset-hash-chain", "unblock-legal-asset", "export-legal-train-dev-test", "decide-rollout-100", "record-rollout-100-metric", "rollback-rollout-100", "publish-metadata-card", "run-takedown-rehearsal", "record-source-drift", "archive-governance-artifact", "record-governance-download", "close-model-blocker", "create-daily-sop-report", "create-weekly-sop-report", "configure-alert-route", "record-live-monitor-sample", "beginTransaction", "rollback()", "commit()"]:
    if snippet not in route: raise SystemExit(f'v55 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV55Routes' not in server: raise SystemExit('server not registering v55 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v55/review-center", "/api/ops/vps/v55/signed-release-certificate", "/api/admin/speech-training/v55/legal-unblocked-dataset", "/api/ops/search/music/v55/rollout-100", "/api/public/music/metadata/v55/publication-cards", "/api/ops/authority-sources/v55/publish-takedown", "/api/ops/speech-training/v55/governance-center", "/api/ops/site/v55/operations-sop", "/api/ops/vps/v55/preflight-contract", "/api/ops/next-upgrade-plan/v56", "/api/internal/vps/v55/sign-release-certificate", "/api/internal/vps/v55/attach-signed-evidence", "/api/internal/vps/v55/archive-certificate-pdf", "/api/internal/vps/v55/reopen-signed-certificate", "/api/internal/speech-training/v55/upload-real-evidence-file", "/api/internal/speech-training/v55/seal-asset-hash-chain", "/api/internal/speech-training/v55/unblock-legal-asset", "/api/internal/speech-training/v55/export-legal-train-dev-test", "/api/internal/search/music/v55/decide-rollout-100", "/api/internal/search/music/v55/record-rollout-100-metric", "/api/internal/search/music/v55/rollback-rollout-100", "/api/internal/authority-sources/v55/publish-metadata-card", "/api/internal/authority-sources/v55/run-takedown-rehearsal", "/api/internal/authority-sources/v55/record-source-drift", "/api/internal/speech-training/v55/archive-governance-artifact", "/api/internal/speech-training/v55/record-governance-download", "/api/internal/speech-training/v55/close-model-blocker", "/api/internal/site/v55/create-daily-sop-report", "/api/internal/site/v55/create-weekly-sop-report", "/api/internal/site/v55/configure-alert-route", "/api/internal/site/v55/record-live-monitor-sample"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 658: raise SystemExit('OpenAPI path count did not increase enough for v55')
plan=json.loads((root/'data/development/next_upgrade_plan_v56.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v56 plan must include 6 items')
print(f"tts/stt music v55 OK: {len(legal.get('assets',[]))} legal candidates, {len(cert.get('checks',[]))} signed certificate checks, {len(search.get('features',[]))} rollout features, {len(auth.get('publication_cards',[]))} metadata cards, {len(site.get('monitors',[]))} monitored routes, {len(api.get('paths',{}))} OpenAPI paths")
