#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/release_certificate_immutable_evidence_v56.json", "data/security/legal_speech_real_export_v56.json", "data/search/music_search_post_rollout_monitoring_v56.json", "data/integration/authority_metadata_public_records_v56.json", "data/audio/speech_model_governance_download_audit_v56.json", "data/site/operations_cadence_v56.json", "data/admin/music_speech_review_center_v56.json", "data/ops/vps_preflight_v56.json", "data/development/next_upgrade_plan_v57.json", "backend/src/rest/ttsSttMusicV56Routes.ts", "frontend-sdk/ttsSttMusicClient.v56.ts", "webapp/components/MusicSpeechReviewCenterV56.tsx", "webapp/app/admin/music-speech/v56/page.tsx", "database/migrations/0052_tts_stt_music_v56.sql", "database/seeds/052_tts_stt_music_v56.sql", "database/seeds/052_production_release_evidence_v56.generated.sql", "database/seeds/052_legal_speech_real_export_v56.generated.sql", "database/seeds/052_search_post_rollout_monitoring_v56.generated.sql", "database/seeds/052_authority_public_records_v56.generated.sql", "database/seeds/052_governance_download_audit_v56.generated.sql", "database/seeds/052_operations_cadence_v56.generated.sql", "deploy/vps-tts-stt-v56.sh", "docs/tts_stt_music_v56.md", "docs/legal_speech_dataset_manifest_v56.generated.md", "docs/release_certificate_immutable_evidence_v56.generated.md", "docs/operations_cadence_v56.generated.md", "docs/next_upgrade_plan_v57.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v56 files: '+', '.join(missing))
release=json.loads((root/'data/deployment/release_certificate_immutable_evidence_v56.json').read_text(encoding='utf-8'))
if len(release.get('checks',[])) < 6 or release.get('summary',{}).get('production_release_allowed') is not False: raise SystemExit('v56 release evidence invalid')
legal=json.loads((root/'data/security/legal_speech_real_export_v56.json').read_text(encoding='utf-8'))
if len(legal.get('assets',[])) != 20 or legal.get('summary',{}).get('dataset_export_allowed') is not False or legal.get('summary',{}).get('train_rows') != 0: raise SystemExit('v56 legal real export invalid')
search=json.loads((root/'data/search/music_search_post_rollout_monitoring_v56.json').read_text(encoding='utf-8'))
if len(search.get('windows',[])) < 3 or search.get('summary',{}).get('auto_rollback_ready') is not True: raise SystemExit('v56 post rollout monitoring invalid')
auth=json.loads((root/'data/integration/authority_metadata_public_records_v56.json').read_text(encoding='utf-8'))
if len(auth.get('publication_cards',[])) < 3 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_lyrics_allowed') is not False: raise SystemExit('v56 authority public records invalid')
model=json.loads((root/'data/audio/speech_model_governance_download_audit_v56.json').read_text(encoding='utf-8'))
if len(model.get('artifacts',[])) < 6 or model.get('summary',{}).get('public_model_release_allowed') is not False: raise SystemExit('v56 governance download audit invalid')
site=json.loads((root/'data/site/operations_cadence_v56.json').read_text(encoding='utf-8'))
if site.get('summary',{}).get('minimum_contrast') != 'WCAG AA' or len(site.get('monitors',[])) < 7: raise SystemExit('v56 operations cadence invalid')
migration=(root/'database/migrations/0052_tts_stt_music_v56.sql').read_text(encoding='utf-8')
for table in ["release_certificate_immutable_artifacts_v56", "release_certificate_backup_evidence_v56", "release_certificate_rollback_observations_v56", "release_certificate_immutable_ledger_v56", "legal_speech_dataset_manifests_v56", "legal_speech_export_artifacts_v56", "legal_speech_blocked_reports_v56", "legal_speech_model_cards_v56", "music_search_post_rollout_24h_metrics_v56", "music_search_post_rollout_72h_metrics_v56", "music_search_post_rollout_incident_rollbacks_v56", "authority_metadata_publication_records_v56", "authority_metadata_sitemap_og_ping_v56", "authority_metadata_takedown_evidence_v56", "speech_model_governance_downloadable_artifacts_v56", "speech_model_governance_audit_queries_v56", "speech_model_governance_signoff_verifications_v56", "site_ops_recurring_daily_jobs_v56", "site_ops_recurring_weekly_jobs_v56", "site_ops_alert_dispatches_v56", "site_ops_cwv_lighthouse_samples_v56"]:
    if table not in migration: raise SystemExit(f'v56 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV56Routes.ts').read_text(encoding='utf-8')
for snippet in ["store-release-pdf-json", "store-cloudflare-dns-evidence", "store-backup-restore-evidence", "store-rollback-observation", "seal-immutable-ledger", "create-dataset-manifest", "export-train-dev-test", "create-blocked-report", "generate-model-card", "record-24h-metric", "record-72h-metric", "trigger-post-rollout-rollback", "store-publication-record", "store-sitemap-og-ping", "store-takedown-evidence", "register-downloadable-artifact", "record-audit-query", "verify-governance-signoff", "create-recurring-daily-job", "create-recurring-weekly-job", "record-alert-dispatch", "record-cwv-lighthouse-sample", "beginTransaction", "rollback()", "commit()"]:
    if snippet not in route: raise SystemExit(f'v56 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV56Routes' not in server: raise SystemExit('server not registering v56 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v56/review-center", "/api/ops/vps/v56/immutable-release-evidence", "/api/admin/speech-training/v56/legal-real-export", "/api/ops/search/music/v56/post-rollout-monitoring", "/api/public/music/metadata/v56/public-records", "/api/ops/authority-sources/v56/public-records", "/api/ops/speech-training/v56/governance-download-audit", "/api/ops/site/v56/operations-cadence", "/api/ops/vps/v56/preflight-contract", "/api/ops/next-upgrade-plan/v57", "/api/internal/vps/v56/store-release-pdf-json", "/api/internal/vps/v56/store-cloudflare-dns-evidence", "/api/internal/vps/v56/store-backup-restore-evidence", "/api/internal/vps/v56/store-rollback-observation", "/api/internal/vps/v56/seal-immutable-ledger", "/api/internal/speech-training/v56/create-dataset-manifest", "/api/internal/speech-training/v56/export-train-dev-test", "/api/internal/speech-training/v56/create-blocked-report", "/api/internal/speech-training/v56/generate-model-card", "/api/internal/search/music/v56/record-24h-metric", "/api/internal/search/music/v56/record-72h-metric", "/api/internal/search/music/v56/trigger-post-rollout-rollback", "/api/internal/authority-sources/v56/store-publication-record", "/api/internal/authority-sources/v56/store-sitemap-og-ping", "/api/internal/authority-sources/v56/store-takedown-evidence", "/api/internal/speech-training/v56/register-downloadable-artifact", "/api/internal/speech-training/v56/record-audit-query", "/api/internal/speech-training/v56/verify-governance-signoff", "/api/internal/site/v56/create-recurring-daily-job", "/api/internal/site/v56/create-recurring-weekly-job", "/api/internal/site/v56/record-alert-dispatch", "/api/internal/site/v56/record-cwv-lighthouse-sample"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 690: raise SystemExit('OpenAPI path count did not increase enough for v56')
plan=json.loads((root/'data/development/next_upgrade_plan_v57.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v57 plan must include 6 items')
print(f"tts/stt music v56 OK: {len(legal.get('assets',[]))} legal export candidates, {len(release.get('checks',[]))} release evidence checks, {len(search.get('windows',[]))} monitoring windows, {len(auth.get('publication_cards',[]))} metadata records, {len(site.get('monitors',[]))} monitored routes, {len(api.get('paths',{}))} OpenAPI paths")
