#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/release_certificate_final_seal_v60.json", "data/security/legal_speech_dataset_immutable_freeze_v60.json", "data/search/music_search_weekly_sla_v60.json", "data/integration/authority_metadata_source_expansion_v60.json", "data/audio/speech_governance_download_alert_closure_v60.json", "data/site/operations_notification_real_delivery_v60.json", "data/admin/music_speech_review_center_v60.json", "data/ops/vps_preflight_v60.json", "data/development/next_upgrade_plan_v61.json", "backend/src/rest/ttsSttMusicV60Routes.ts", "frontend-sdk/ttsSttMusicClient.v60.ts", "webapp/components/MusicSpeechReviewCenterV60.tsx", "webapp/app/admin/music-speech/v60/page.tsx", "database/migrations/0056_tts_stt_music_v60.sql", "database/seeds/056_tts_stt_music_v60.sql", "database/seeds/056_production_final_seal_v60.generated.sql", "database/seeds/056_legal_speech_immutable_freeze_v60.generated.sql", "database/seeds/056_search_weekly_sla_v60.generated.sql", "database/seeds/056_authority_source_expansion_v60.generated.sql", "database/seeds/056_governance_alert_closure_v60.generated.sql", "database/seeds/056_operations_real_delivery_v60.generated.sql", "deploy/vps-tts-stt-v60.sh", "docs/tts_stt_music_v60.md", "docs/release_certificate_final_seal_v60.generated.md", "docs/legal_speech_dataset_immutable_freeze_v60.generated.md", "docs/operations_real_delivery_v60.generated.md", "docs/next_upgrade_plan_v61.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v60 files: '+', '.join(missing))
release=json.loads((root/'data/deployment/release_certificate_final_seal_v60.json').read_text(encoding='utf-8'))
if len(release.get('checks',[])) < 6 or release.get('summary',{}).get('final_sealed_on_real_vps') is not False: raise SystemExit('v60 final seal invalid')
dataset=json.loads((root/'data/security/legal_speech_dataset_immutable_freeze_v60.json').read_text(encoding='utf-8'))
if len(dataset.get('assets',[])) != 20 or dataset.get('summary',{}).get('dataset_frozen') is not False or dataset.get('summary',{}).get('train_rows') != 0: raise SystemExit('v60 dataset immutable freeze gate invalid')
search=json.loads((root/'data/search/music_search_weekly_sla_v60.json').read_text(encoding='utf-8'))
if len(search.get('features',[])) < 3 or search.get('summary',{}).get('weekly_quality_report_ready') is not True: raise SystemExit('v60 search weekly SLA invalid')
auth=json.loads((root/'data/integration/authority_metadata_source_expansion_v60.json').read_text(encoding='utf-8'))
if len(auth.get('records',[])) < 8 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_full_lyrics_allowed') is not False: raise SystemExit('v60 authority source expansion invalid')
gov=json.loads((root/'data/audio/speech_governance_download_alert_closure_v60.json').read_text(encoding='utf-8'))
if len(gov.get('artifacts',[])) < 6 or gov.get('summary',{}).get('ack_close_loop_ready') is not True: raise SystemExit('v60 governance alert closure invalid')
ops=json.loads((root/'data/site/operations_notification_real_delivery_v60.json').read_text(encoding='utf-8'))
if len(ops.get('jobs',[])) < 6 or ops.get('summary',{}).get('real_delivery_verified') is not False: raise SystemExit('v60 operations real delivery invalid')
migration=(root/'database/migrations/0056_tts_stt_music_v60.sql').read_text(encoding='utf-8')
for table in ["release_certificate_final_seals_v60", "release_restore_final_verifications_v60", "release_rollback_final_verifications_v60", "release_dns_cloudflare_final_verifications_v60", "release_observation_final_verifications_v60", "release_hash_chain_final_verifications_v60", "legal_speech_dataset_immutable_freezes_v60", "legal_speech_final_train_dev_test_exports_v60", "legal_speech_dataset_version_locks_v60", "legal_speech_final_checksum_manifests_v60", "legal_speech_final_model_cards_v60", "search_weekly_quality_reports_v60", "search_anomaly_sla_tasks_v60", "search_policy_regression_tests_v60", "search_rollback_drills_v60", "authority_metadata_source_expansions_v60", "authority_citation_evidence_seals_v60", "authority_takedown_evidence_seals_v60", "authority_source_drift_evidence_seals_v60", "governance_download_alerts_v60", "governance_download_alert_acks_v60", "governance_download_alert_closures_v60", "governance_weekly_audit_reports_v60", "governance_rbac_download_tests_v60", "operations_notification_deliveries_v60", "operations_notification_acks_v60", "operations_notification_escalations_v60", "operations_notification_closures_v60", "operations_weekly_improvement_tasks_v60"]:
    if table not in migration: raise SystemExit(f'v60 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV60Routes.ts').read_text(encoding='utf-8')
for snippet in ['record-final-seal','freeze-immutable-dataset','export-final-train-dev-test','write-weekly-quality-report','record-source-expansion','record-download-alert','record-notification-delivery','beginTransaction','rollback','commit']:
    if snippet not in route: raise SystemExit(f'v60 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV60Routes' not in server: raise SystemExit('server not registering v60 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v60/review-center", "/api/ops/vps/v60/final-seal", "/api/admin/speech-training/v60/immutable-freeze", "/api/ops/search/music/v60/weekly-sla", "/api/ops/authority-sources/v60/source-expansion", "/api/ops/speech-training/v60/governance-alert-closure", "/api/ops/site/v60/real-delivery", "/api/ops/vps/v60/preflight-contract", "/api/ops/next-upgrade-plan/v61", "/api/internal/vps/v60/record-final-seal", "/api/internal/vps/v60/record-restore-final-verification", "/api/internal/vps/v60/record-rollback-final-verification", "/api/internal/vps/v60/record-dns-cloudflare-final-verification", "/api/internal/vps/v60/record-observation-final-verification", "/api/internal/vps/v60/record-hash-chain-final-verification", "/api/internal/speech-training/v60/freeze-immutable-dataset", "/api/internal/speech-training/v60/export-final-train-dev-test", "/api/internal/speech-training/v60/lock-dataset-version", "/api/internal/speech-training/v60/write-final-checksum-manifest", "/api/internal/speech-training/v60/write-final-model-card", "/api/internal/search/music/v60/write-weekly-quality-report", "/api/internal/search/music/v60/create-anomaly-sla-task", "/api/internal/search/music/v60/record-policy-regression-test", "/api/internal/search/music/v60/record-rollback-drill", "/api/internal/authority/v60/record-source-expansion", "/api/internal/authority/v60/seal-citation-evidence", "/api/internal/authority/v60/seal-takedown-evidence", "/api/internal/authority/v60/seal-source-drift-evidence", "/api/internal/governance/v60/record-download-alert", "/api/internal/governance/v60/ack-download-alert", "/api/internal/governance/v60/close-download-alert", "/api/internal/governance/v60/write-weekly-audit-report", "/api/internal/governance/v60/write-rbac-download-test", "/api/internal/ops/v60/record-notification-delivery", "/api/internal/ops/v60/ack-notification", "/api/internal/ops/v60/escalate-notification", "/api/internal/ops/v60/close-notification", "/api/internal/ops/v60/create-weekly-improvement-task"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 830: raise SystemExit('OpenAPI path count did not increase enough for v60')
plan=json.loads((root/'data/development/next_upgrade_plan_v61.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v61 plan must include 6 items')
print(f"tts/stt music v60 OK: {len(dataset.get('assets',[]))} dataset candidates, {len(release.get('checks',[]))} final seal checks, {len(search.get('features',[]))} search features, {len(auth.get('records',[]))} metadata records, {len(ops.get('jobs',[]))} delivery jobs, {len(api.get('paths',{}))} OpenAPI paths")
