#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
root=Path.cwd()
required=["data/deployment/production_release_certificate_sealed_v58.json", "data/security/legal_speech_dataset_v58_0.json", "data/search/music_search_formal_config_v58.json", "data/integration/authority_metadata_audit_seal_v58.json", "data/audio/speech_governance_rbac_download_v58.json", "data/site/operations_live_delivery_v58.json", "data/admin/music_speech_review_center_v58.json", "data/ops/vps_preflight_v58.json", "data/development/next_upgrade_plan_v59.json", "backend/src/rest/ttsSttMusicV58Routes.ts", "frontend-sdk/ttsSttMusicClient.v58.ts", "webapp/components/MusicSpeechReviewCenterV58.tsx", "webapp/app/admin/music-speech/v58/page.tsx", "database/migrations/0054_tts_stt_music_v58.sql", "database/seeds/054_tts_stt_music_v58.sql", "database/seeds/054_production_release_certificate_v58.generated.sql", "database/seeds/054_legal_speech_dataset_v58.generated.sql", "database/seeds/054_search_formal_config_v58.generated.sql", "database/seeds/054_authority_metadata_audit_v58.generated.sql", "database/seeds/054_governance_rbac_download_v58.generated.sql", "database/seeds/054_operations_live_delivery_v58.generated.sql", "deploy/vps-tts-stt-v58.sh", "docs/tts_stt_music_v58.md", "docs/legal_speech_dataset_v58.generated.md", "docs/production_release_certificate_sealed_v58.generated.md", "docs/operations_live_delivery_v58.generated.md", "docs/next_upgrade_plan_v59.md"]
missing=[p for p in required if not (root/p).exists()]
if missing: raise SystemExit('missing required v58 files: '+', '.join(missing))
release=json.loads((root/'data/deployment/production_release_certificate_sealed_v58.json').read_text(encoding='utf-8'))
if len(release.get('checks',[])) < 6 or release.get('summary',{}).get('production_release_certificate_sealed') is not False: raise SystemExit('v58 release certificate seal invalid')
dataset=json.loads((root/'data/security/legal_speech_dataset_v58_0.json').read_text(encoding='utf-8'))
if len(dataset.get('assets',[])) != 20 or dataset.get('summary',{}).get('dataset_export_allowed') is not False or dataset.get('summary',{}).get('train_rows') != 0: raise SystemExit('v58 dataset gate invalid')
search=json.loads((root/'data/search/music_search_formal_config_v58.json').read_text(encoding='utf-8'))
if len(search.get('features',[])) < 3 or search.get('summary',{}).get('rollback_ready') is not True: raise SystemExit('v58 search formal config invalid')
auth=json.loads((root/'data/integration/authority_metadata_audit_seal_v58.json').read_text(encoding='utf-8'))
if len(auth.get('records',[])) < 3 or auth.get('summary',{}).get('public_audio_allowed') is not False or auth.get('summary',{}).get('public_lyrics_allowed') is not False: raise SystemExit('v58 authority audit invalid')
gov=json.loads((root/'data/audio/speech_governance_rbac_download_v58.json').read_text(encoding='utf-8'))
if len(gov.get('artifacts',[])) < 6 or len(gov.get('permission_tests',[])) < 6 or gov.get('summary',{}).get('download_watermark_required') is not True: raise SystemExit('v58 governance rbac download invalid')
site=json.loads((root/'data/site/operations_live_delivery_v58.json').read_text(encoding='utf-8'))
if site.get('summary',{}).get('minimum_contrast') != 'WCAG AA' or len(site.get('report_jobs',[])) < 6: raise SystemExit('v58 operations live delivery invalid')
migration=(root/'database/migrations/0054_tts_stt_music_v58.sql').read_text(encoding='utf-8')
for table in ["release_certificate_immutable_seals_v58", "release_evidence_ledger_entries_v58", "release_backup_restore_evidence_v58", "release_dns_cloudflare_evidence_v58", "release_observation_evidence_v58", "release_hash_chain_verifications_v58", "legal_speech_dataset_exports_v58", "legal_speech_dataset_manifests_v58", "legal_speech_dataset_checksums_v58", "legal_speech_dataset_blocked_reports_v58", "legal_speech_model_cards_v58", "search_formal_config_decisions_v58", "search_100_rollout_monitoring_v58", "search_anomaly_human_tasks_v58", "search_rollback_events_v58", "authority_metadata_audit_seals_v58", "authority_metadata_sitemap_og_evidence_v58", "authority_metadata_citation_evidence_v58", "authority_metadata_takedown_evidence_v58", "governance_artifact_downloads_v58", "governance_permission_tests_v58", "governance_audit_exports_v58", "governance_watermark_events_v58", "site_ops_report_deliveries_v58", "site_ops_channel_tests_v58", "site_ops_alert_escalations_v58"]:
    if table not in migration: raise SystemExit(f'v58 migration missing {table}')
route=(root/'backend/src/rest/ttsSttMusicV58Routes.ts').read_text(encoding='utf-8')
for snippet in ["ingest-release-certificate", "ingest-release-evidence", "record-backup-restore-evidence", "record-dns-cloudflare-evidence", "record-30m-observation", "verify-hash-chain", "export-dataset", "write-dataset-manifest", "write-checksum", "write-blocked-report", "write-model-card", "apply-formal-config", "record-rollout-monitoring", "create-human-task", "rollback-feature", "seal-audit-record", "store-sitemap-og-evidence", "store-citation-evidence", "store-takedown-evidence", "download-artifact", "run-permission-test", "export-audit", "write-watermark-event", "send-report", "test-channel", "escalate-alert", "beginTransaction", "rollback()", "commit()"]:
    if snippet not in route: raise SystemExit(f'v58 route missing {snippet}')
server=(root/'backend/src/server.ts').read_text(encoding='utf-8')
if 'registerTtsSttMusicV58Routes' not in server: raise SystemExit('server not registering v58 routes')
api=json.loads((root/'openapi/pinuyumayan-main-site-api.openapi.json').read_text(encoding='utf-8'))
for path in ["/api/admin/music-speech/v58/review-center", "/api/ops/vps/v58/release-certificate-sealed", "/api/admin/speech-training/v58/dataset-v58", "/api/ops/search/music/v58/formal-config", "/api/ops/authority-sources/v58/audit-seal", "/api/ops/speech-training/v58/governance-rbac-download", "/api/ops/site/v58/live-delivery", "/api/ops/vps/v58/preflight-contract", "/api/ops/next-upgrade-plan/v59", "/api/internal/vps/v58/ingest-release-certificate", "/api/internal/vps/v58/ingest-release-evidence", "/api/internal/vps/v58/record-backup-restore-evidence", "/api/internal/vps/v58/record-dns-cloudflare-evidence", "/api/internal/vps/v58/record-30m-observation", "/api/internal/vps/v58/verify-hash-chain", "/api/internal/speech-training/v58/export-dataset", "/api/internal/speech-training/v58/write-dataset-manifest", "/api/internal/speech-training/v58/write-checksum", "/api/internal/speech-training/v58/write-blocked-report", "/api/internal/speech-training/v58/write-model-card", "/api/internal/search/music/v58/apply-formal-config", "/api/internal/search/music/v58/record-rollout-monitoring", "/api/internal/search/music/v58/create-human-task", "/api/internal/search/music/v58/rollback-feature", "/api/internal/authority-sources/v58/seal-audit-record", "/api/internal/authority-sources/v58/store-sitemap-og-evidence", "/api/internal/authority-sources/v58/store-citation-evidence", "/api/internal/authority-sources/v58/store-takedown-evidence", "/api/internal/governance/v58/download-artifact", "/api/internal/governance/v58/run-permission-test", "/api/internal/governance/v58/export-audit", "/api/internal/governance/v58/write-watermark-event", "/api/internal/site/v58/send-report", "/api/internal/site/v58/test-channel", "/api/internal/site/v58/escalate-alert"]:
    if path not in api.get('paths',{}): raise SystemExit(f'OpenAPI missing {path}')
if len(api.get('paths',{})) < 758: raise SystemExit('OpenAPI path count did not increase enough for v58')
plan=json.loads((root/'data/development/next_upgrade_plan_v59.json').read_text(encoding='utf-8'))
if len(plan.get('items',[])) != 6: raise SystemExit('v59 plan must include 6 items')
print(f"tts/stt music v58 OK: {len(dataset.get('assets',[]))} dataset candidates, {len(release.get('checks',[]))} certificate checks, {len(search.get('features',[]))} search features, {len(auth.get('records',[]))} metadata audit records, {len(site.get('report_jobs',[]))} delivery jobs, {len(api.get('paths',{}))} OpenAPI paths")
